function Artlist(usrarr){
var Art={art1:['name', 'territory', 'union'],
art2:['admission', 'establishment', 'new', 'states'],
art3:['formation', 'new', 'states', 'alteration', 'areas', 'boundaries', 'names', 'existing', 'states'],
art4:['laws', 'made', 'under', 'articles', '2', '3', 'provide', 'amendment', 'first', 'fourth', 'schedules', 'supplemental', 'incidental', 'and', 'consequential', 'matters'],
art5:['citizenship', 'commencement', 'constitution'],
art6:['rights', 'citizenship', 'certain', 'persons', 'migrated', 'india', 'pakistan'],
art7:['rights', 'citizenship', 'certain', 'migrants', 'pakistan'],
art8:['rights', 'citizenship', 'certain', 'persons', 'indian', 'origin', 'residing', 'outside', 'india'],
art9:['persons', 'voluntarily', 'acquiring', 'citizenship', 'foreign', 'state', 'not', 'citizens'],
art10:['continuance', 'rights', 'citizenship'],
art11:['parliament', 'regulate', 'right', 'citizenship', 'law'],
art12:['definition'],
art13:['laws', 'inconsistent', 'derogation', 'fundamental', 'rights'],
art14:['equality', 'before', 'law'],
art15:['prohibition', 'discrimination', 'grounds', 'religion', 'race', 'caste', 'sex', 'place', 'birth'],
art16:['equality', 'opportunity', 'matters', 'public', 'employment'],
art17:['abolition', 'untouchability'],
art18:['abolition', 'titles'],
art19:['protection', 'certain', 'rights', 'regarding', 'freedom', 'speech', 'etc'],
art20:['protection', 'respect', 'conviction', 'offences'],
art21:['protection', 'life', 'personal', 'liberty'],
art21A:['right', 'educatio'],
art22:['protection', 'against', 'arrest', 'detention', 'certain', 'cases'],
art23:['prohibition', 'traffic', 'human', 'beings', 'forced', 'labour'],
art24:['prohibition', 'employment', 'children', 'factories', 'etc'],
art25:['freedom', 'conscience', 'free', 'profession', 'practice', 'propagation', 'religion'],
art26:['freedom', 'manage', 'religious', 'affairs'],
art27:['freedom', 'payment', 'taxes', 'promotion', 'any', 'particular', 'religion'],
art28:['freedom', 'attendance', 'religious', 'instruction', 'religious', 'worship', 'certain', 'educational', 'institutions'],
art29:['protection', 'interests', 'minorities'],
art30:['right', 'minorities', 'establish', 'administer', 'educational', 'institutions'],
art31A:['saving', 'laws', 'providing', 'acquisition', 'estates', 'etc'],
art31B:['validation', 'certain', 'acts', 'regulations'],
art31C:['saving', 'laws', 'giving', 'effect', 'certain', 'directive', 'principles'],
art32:['remedies', 'enforcement', 'rights', 'conferred', 'part'],
art33:['power', 'parliament', 'modify', 'rights', 'conferred', 'part', 'their', 'application', 'forces', 'etc'],
art34:['restriction', 'rights', 'conferred', 'part', 'while', 'martial', 'law', 'force', 'any', 'area'],
art35:['legislation', 'give', 'effect', 'provisions', 'part'],
art36:['definition'],
art37:['application', 'principles', 'contained', 'part'],
art38:['state', 'secure', 'social', 'order', 'promotion', 'welfare', 'people'],
art39:['certain', 'principles', 'policy', 'followed', 'state'],
art39A:['equal', 'justice', 'free', 'legal', 'aid'],
art40:['organisation', 'village', 'panchayats'],
art41:['right', 'work', 'education', 'public', 'assistance', 'certain', 'cases'],
art42:['provision', 'just', 'humane', 'conditions', 'work', 'maternity', 'relief'],
art43:['living', 'wage', 'etc.', 'workers'],
art43A:['participation', 'workers', 'management', 'industries'],
art43B:['promotion', 'co-operative', 'societies'],
art44:['uniform', 'civil', 'code', 'citizens'],
art45:['provision', 'free', 'compulsory', 'education', 'children'],
art46:['promotion', 'educational', 'economic', 'interests', 'scheduled', 'castes', 'scheduled', 'tribes', 'other', 'weaker', 'sections'],
art47:['duty', 'state', 'raise', 'level', 'nutrition', 'standard', 'living', 'improve', 'public', 'health'],
art48:['organisation', 'agriculture', 'animal', 'husbandry'],
art48A:['protection', 'improvement', 'environment', 'safeguarding', 'forests', 'wildlife'],
art49:['protection', 'monuments', 'places', 'objects', 'national', 'importance'],
art50:['separation', 'judiciary', 'executive'],
art51:['promotion', 'international', 'peace', 'security'],
art51A:['fundamental', 'duties'],
art52:['president', 'india'],
art53:['executive', 'power', 'union'],
art54:['election', 'president'],
art55:['manner', 'election', 'president'],
art56:['term', 'office', 'president'],
art57:['eligibility', 're-election'],
art58:['qualifications', 'election', 'president'],
art59:['conditions', 'president�s', 'office'],
art60:['oath', 'affirmation', 'president'],
art61:['procedure', 'impeachment', 'president'],
art62:['time', 'holding', 'election', 'fill', 'vacancy', 'office', 'president', 'term', 'office', 'of', 'person', 'elected', 'fill', 'casual', 'vacancy'],
art63:['vice-president', 'india'],
art64:['vice-president', 'ex', 'officio', 'chairman', 'council', 'states'],
art65:['vice-president', 'act', 'president', 'discharge', 'his', 'functions', 'during', 'casual', 'vacancies', 'office', 'during', 'absence', 'president'],
art66:['election', 'vice-president'],
art67:['term', 'office', 'vice-president'],
art68:['time', 'holding', 'election', 'fill', 'vacancy', 'office', 'vice-president', 'term', 'office', 'of', 'person', 'elected', 'fill', 'casual', 'vacancy'],
art69:['oath', 'affirmation', 'vice-president'],
art70:['discharge', 'president�s', 'functions', 'other', 'contingencies'],
art71:['matters', 'relating', 'connected', 'election', 'president', 'vice-president'],
art72:['power', 'president', 'grant', 'pardons', 'etc.', 'suspend', 'remit', 'commute', 'sentences', 'certain', 'cases'],
art73:['extent', 'executive', 'power', 'union'],
art74:['council', 'ministers', 'aid', 'advise', 'president'],
art75:['other', 'provisions', 'ministers'],
art76:['attorney-general', 'india'],
art77:['conduct', 'business', 'government', 'india'],
art78:['duties', 'prime', 'minister', 'respects', 'furnishing', 'information', 'president', 'etc'],
art79:['constitution', 'parliament'],
art80:['composition', 'council', 'states'],
art81:['composition', 'house', 'people'],
art82:['readjustment', 'after', 'each', 'census'],
art83:['duration', 'houses', 'parliament'],
art84:['qualification', 'membership', 'parliament'],
art85:['sessions', 'parliament', 'prorogation', 'dissolution'],
art86:['right', 'president', 'address', 'send', 'messages', 'houses'],
art87:['special', 'address', 'president'],
art88:['rights', 'ministers', 'attorney-general', 'respects', 'houses'],
art89:['chairman', 'deputy', 'chairman', 'council', 'states'],
art90:['vacation', 'resignation', 'removal', 'office', 'deputy', 'chairman'],
art91:['power', 'deputy', 'chairman', 'other', 'person', 'perform', 'duties', 'office', 'act', 'chairman'],
art92:['chairman', 'deputy', 'chairman', 'not', 'preside', 'while', 'resolution', 'his', 'removal', 'office', 'under', 'consideration'],
art93:['speaker', 'deputy', 'speaker', 'house', 'people'],
art94:['vacation', 'resignation', 'removal', 'offices', 'speaker', 'deputy', 'speaker'],
art95:['power', 'deputy', 'speaker', 'other', 'person', 'perform', 'duties', 'office', 'act', 'speaker'],
art96:['speaker', 'deputy', 'speaker', 'not', 'preside', 'while', 'resolution', 'his', 'removal', 'office', 'under', 'consideration'],
art97:['salaries', 'allowances', 'chairman', 'deputy', 'chairman', 'speaker', 'and', 'deputy', 'speaker'],
art98:['secretariat', 'parliament'],
art99:['oath', 'affirmation', 'members'],
art100:['voting', 'houses', 'power', 'houses', 'act', 'notwithstanding', 'vacancies', 'quorum'],
art101:['vacation', 'seats'],
art102:['disqualifications', 'membership'],
art103:['decision', 'questions', 'disqualifications', 'members'],
art104:['penalty', 'sitting', 'voting', 'before', 'making', 'oath', 'affirmation', 'under', 'article', '99', 'when', 'not', 'qualified', 'when', 'disqualified'],
art105:['powers', 'privileges', 'etc.', 'houses', 'parliament', 'members', 'committees', 'thereof'],
art106:['salaries', 'allowances', 'members'],
art107:['provisions', 'introduction', 'passing', 'bills'],
art108:['joint', 'sitting', 'both', 'houses', 'certain', 'cases'],
art109:['special', 'procedure', 'respect', 'money', 'bills'],
art110:['definition', '�money', 'bills�'],
art111:['assent', 'bills'],
art112:['annual', 'financial', 'statement'],
art113:['procedure', 'parliament', 'respect', 'estimates'],
art114:['appropriation', 'bills'],
art115:['supplementary', 'additional', 'excess', 'grants'],
art116:['votes', 'account', 'votes', 'credit', 'exceptional', 'grants'],
art117:['special', 'provisions', 'financial', 'bills'],
art118:['rules', 'procedure'],
art119:['regulation', 'law', 'procedure', 'parliament', 'relation', 'financial', 'business'],
art120:['language', 'used', 'parliament'],
art121:['restriction', 'discussion', 'parliament'],
art122:['courts', 'not', 'inquire', 'into', 'proceedings', 'parliament'],
art123:['power', 'president', 'promulgate', 'ordinances', 'during', 'recess', 'parliament'],
art124:['establishment', 'constitution', 'supreme', 'court'],
art124A:['national', 'judicial', 'appointments', 'commission.', '(declared', 'unconstitutional', 'supreme', 'court', 'however', 'not', 'repealed', 'parliament'],
art124B:['functions', 'commission'],
art124C:['power', 'parliament', 'make', 'law'],
art125:['salaries', 'etc.', 'judges'],
art126:['appointment', 'acting', 'chief', 'justice'],
art127:['appointment', 'ad', 'hoc', 'judges'],
art128:['attendance', 'retired', 'judges', 'sittings', 'supreme', 'court'],
art129:['supreme', 'court', 'court', 'record'],
art130:['seat', 'supreme', 'court'],
art131:['original', 'jurisdiction', 'supreme', 'court'],
art132:['appellate', 'jurisdiction', 'supreme', 'court', 'appeals', 'high', 'courts', 'certain', 'cases'],
art133:['appellate', 'jurisdiction', 'supreme', 'court', 'appeals', 'high', 'courts', 'regard', 'civil', 'matters'],
art134:['appellate', 'jurisdiction', 'supreme', 'court', 'regard', 'criminal', 'matters'],
art134A:['certificate', 'appeal', 'supreme', 'court'],
art135:['jurisdiction', 'powers', 'federal', 'court', 'under', 'existing', 'law', 'exercisable', 'supreme', 'court'],
art136:['special', 'leave', 'appeal', 'supreme', 'court'],
art137:['review', 'judgments', 'orders', 'supreme', 'court'],
art138:['enlargement', 'jurisdiction', 'supreme', 'court'],
art139:['conferment', 'supreme', 'court', 'powers', 'issue', 'certain', 'writs'],
art139A:['transfer', 'certain', 'cases'],
art140:['ancillary', 'powers', 'supreme', 'court'],
art141:['law', 'declared', 'supreme', 'court', 'binding', 'courts'],
art142:['enforcement', 'decrees', 'orders', 'supreme', 'court', 'orders', 'discovery', 'etc'],
art143:['power', 'president', 'consult', 'supreme', 'court'],
art144:['civil', 'judicial', 'authorities', 'act', 'aid', 'supreme', 'court'],
art145:['rules', 'court', 'etc'],
art146:['officers', 'servants', 'expenses', 'supreme', 'court'],
art147:['interpretation'],
art148:['comptroller', 'auditor-general', 'india'],
art149:['duties', 'powers', 'comptroller', 'auditor-general'],
art150:['form', 'accounts', 'union', 'states'],
art151:['audit', 'reports'],
art152:['definition'],
art153:['governors', 'states'],
art154:['executive', 'power', 'state'],
art155:['appointment', 'governor'],
art156:['term', 'office', 'governor'],
art157:['qualifications', 'appointment', 'governor'],
art158:['conditions', 'governor�s', 'offic'],
art159:['oath', 'affirmation', 'governor'],
art160:['discharge', 'functions', 'governor', 'certain', 'contingencies'],
art161:['power', 'governor', 'grant', 'pardons', 'etc.', 'suspend', 'remit', 'commute', 'sentences', 'certain', 'cases'],
art162:['extent', 'executive', 'power', 'state'],
art163:['council', 'ministers', 'aid', 'advise', 'governor'],
art164:['other', 'provisions', 'ministers'],
art165:['advocate-general', 'state'],
art166:['conduct', 'business', 'government', 'state'],
art167:['duties', 'chief', 'minister', 'respects', 'furnishing', 'information', 'governor', 'etc'],
art168:['constitution', 'legislatures', 'states'],
art169:['abolition', 'creation', 'legislative', 'councils', 'states'],
art170:['composition', 'legislative', 'assemblies'],
art171:['composition', 'legislative', 'councils'],
art172:['duration', 'state', 'legislatures'],
art173:['qualification', 'membership', 'state', 'legislature'],
art174:['sessions', 'state', 'legislature', 'prorogation', 'dissolution'],
art175:['right', 'governor', 'address', 'send', 'messages', 'house', 'houses'],
art176:['special', 'address', 'governor'],
art177:['rights', 'ministers', 'advocate-general', 'respects', 'houses'],
art178:['speaker', 'deputy', 'speaker', 'legislative', 'assembly'],
art179:['vacation', 'resignation', 'removal', 'offices', 'speaker', 'deputy', 'speaker'],
art180:['power', 'deputy', 'speaker', 'other', 'person', 'perform', 'duties', 'office', 'act', 'speaker'],
art181:['speaker', 'deputy', 'speaker', 'not', 'preside', 'while', 'resolution', 'his', 'removal', 'office', 'under', 'consideration'],
art182:['chairman', 'deputy', 'chairman', 'legislative', 'council'],
art183:['vacation', 'resignation', 'removal', 'offices', 'chairman', 'deputy', 'chairman'],
art184:['power', 'deputy', 'chairman', 'other', 'person', 'perform', 'duties', 'office', 'act', 'chairman'],
art185:['chairman', 'deputy', 'chairman', 'not', 'preside', 'while', 'resolution', 'his', 'removal', 'office', 'under', 'consideration'],
art186:['salaries', 'allowances', 'speaker', 'deputy', 'speaker', 'chairman', 'and', 'deputy', 'chairman'],
art187:['secretariat', 'state', 'legislature'],
art188:['oath', 'affirmation', 'members'],
art189:['voting', 'houses', 'power', 'houses', 'act', 'notwithstanding', 'vacancies', 'quorum'],
art190:['vacation', 'seats'],
art191:['disqualifications', 'membership'],
art192:['decision', 'questions', 'disqualifications', 'members'],
art193:['penalty', 'sitting', 'voting', 'before', 'making', 'oath', 'affirmation', 'under', 'article', '188', 'when', 'not', 'qualified', 'when', 'disqualified'],
art194:['powers', 'privileges', 'etc.', 'houses', 'legislatures', 'members', 'committees', 'thereof'],
art195:['salaries', 'allowances', 'members'],
art196:['provisions', 'introduction', 'passing', 'bills'],
art197:['restriction', 'powers', 'legislative', 'council', 'bills', 'other', 'than', 'money', 'bills'],
art198:['special', 'procedure', 'respect', 'money', 'bills'],
art199:['definition', 'money', 'bills'],
art200:['assent', 'bills'],
art201:['bills', 'reserved', 'consideration'],
art202:['annual', 'financial', 'statement'],
art203:['procedure', 'legislature', 'respect', 'estimates'],
art204:['appropriation', 'bills'],
art205:['supplementary', 'additional', 'excess', 'grants'],
art206:['votes', 'account', 'votes', 'credit', 'exceptional', 'grants'],
art207:['special', 'provisions', 'financial', 'bills'],
art208:['rules', 'procedure'],
art209:['regulation', 'law', 'procedure', 'legislature', 'state', 'relation', 'financial', 'business'],
art210:['language', 'used', 'legislature'],
art211:['restriction', 'discussion', 'legislature'],
art212:['courts', 'not', 'inquire', 'into', 'proceedings', 'legislature'],
art213:['power', 'governor', 'promulgate', 'ordinances', 'during', 'recess', 'legislature'],
art214:['high', 'courts', 'states'],
art215:['high', 'courts', 'courts', 'record'],
art216:['constitution', 'high', 'courts'],
art217:['appointment', 'conditions', 'office', 'judge', 'high', 'court'],
art218:['application', 'certain', 'provisions', 'relating', 'supreme', 'court', 'high', 'courts'],
art219:['oath', 'affirmation', 'judges', 'high', 'courts'],
art220:['restriction', 'practice', 'after', 'permanent', 'judge'],
art221:['salaries', 'etc.', 'judges'],
art222:['transfer', 'judge', 'one', 'high', 'court', 'another'],
art223:['appointment', 'acting', 'chief', 'justice'],
art224:['appointment', 'additional', 'acting', 'judges'],
art224A:['appointment', 'retired', 'judges', 'sittings', 'high', 'courts'],
art225:['jurisdiction', 'existing', 'high', 'courts'],
art226:['power', 'high', 'courts', 'issue', 'certain', 'writs'],
art227:['power', 'superintendence', 'over', 'courts', 'high', 'court'],
art228:['transfer', 'certain', 'cases', 'high', 'court'],
art229:['officers', 'servants', 'expenses', 'high', 'courts'],
art230:['extension', 'jurisdiction', 'high', 'courts', 'union', 'territories'],
art231:['establishment', 'common', 'high', 'court', 'two', 'more', 'states'],
art233:['appointment', 'district', 'judges'],
art233A:['validation', 'appointments', 'judgments', 'etc.', 'delivered', 'certain', 'district', 'judges'],
art234:['recruitment', 'persons', 'other', 'than', 'district', 'judges', 'judicial', 'service'],
art235:['control', 'over', 'subordinate', 'courts'],
art236:['interpretation'],
art237:['application', 'provisions', 'chapter', 'certain', 'class', 'classes', 'magistrates'],
art239:['administration', 'union', 'territories'],
art239A:['creation', 'local', 'legislatures', 'council', 'ministers', 'both', 'certain', 'union', 'territories'],
art239AA:['special', 'provisions', 'respect', 'delhi'],
art239AB:['provision', 'case', 'failure', 'constitutional', 'machinery'],
art239B:['power', 'administrator', 'promulgate', 'ordinances', 'during', 'recess', 'legislature'],
art240:['power', 'president', 'make', 'regulations', 'certain', 'union', 'territories'],
art241:['high', 'courts', 'union', 'territories'],
art243:['definitions'],
art243A:['gram', 'sabha'],
art243B:['constitution', 'panchayats'],
art243C:['composition', 'panchayats'],
art243D:['reservation', 'seats'],
art243E:['duration', 'panchayats', 'etc'],
art243F:['disqualifications', 'membership'],
art243G:['powers', 'authority', 'responsibilities', 'panchayats'],
art243H:['powers', 'impose', 'taxes', 'funds', 'panchayats'],
art243I:['constitution', 'finance', 'commission', 'review', 'financial', 'position'],
art243J:['audit', 'accounts', 'panchayats'],
art243K:['elections', 'panchayats'],
art243L:['application', 'union', 'territories'],
art243M:['part', 'not', 'apply', 'certain', 'areas'],
art243N:['continuance', 'existing', 'laws', 'panchayats'],
art243O:['bar', 'interference', 'courts', 'electoral', 'matters'],
art243P:['definitions'],
art243Q:['constitution', 'municipalities'],
art243R:['composition', 'municipalities'],
art243S:['constitution', 'composition', 'wards', 'committees', 'etc'],
art243T:['reservation', 'seats'],
art243U:['duration', 'municipalities', 'etc'],
art243V:['disqualifications', 'membership'],
art243W:['powers', 'authority', 'responsibilities', 'municipalities', 'etc'],
art243X:['power', 'impose', 'taxes', 'funds', 'municipalities'],
art243Y:['finance', 'commission'],
art243Z:['audit', 'accounts', 'municipalities'],
art243ZA:['elections', 'municipalities'],
art243ZB:['application', 'union', 'territories'],
art243ZC:['part', 'not', 'apply', 'certain', 'areas'],
art243ZD:['committee', 'district', 'planning'],
art243ZE:['committee', 'metropolitan', 'planning'],
art243ZF:['continuance', 'existing', 'laws', 'municipalities'],
art243ZG:['bar', 'interference', 'courts', 'electoral', 'matters'],
art243ZH:['definition'],
art243ZI:['incorporation', 'co-operative', 'societie'],
art243ZJ:['number', 'term', 'members', 'board', 'its', 'office', 'bearers'],
art243ZK:['zk', 'election', 'members', 'board'],
art243ZL:['supersession', 'suspension', 'board', 'interim', 'management'],
art243ZM:['audit', 'accounts', 'co-operative', 'societies'],
art243ZN:['convening', 'general', 'body', 'meetings'],
art243ZO:['right', 'member', 'get', 'information'],
art243ZP:['returns'],
art243ZQ:['offences', 'penalties'],
art243ZR:['application', 'multi-state', 'co-operative', 'societies'],
art243ZS:['application', 'union', 'territories'],
art243ZT:['continuance', 'existing', 'laws'],
art244:['administration', 'scheduled', 'areas', 'tribal', 'areas'],
art244A:['formation', 'an', 'autonomous', 'state', 'comprising', 'certain', 'tribal', 'areas', 'assam', 'creation', 'local', 'legislature', 'council', 'ministers', 'both', 'therefor'],
art245:['extent', 'laws', 'made', 'parliament', 'legislatures', 'states'],
art246:['subject-matter', 'laws', 'made', 'parliament', 'legislatures', 'states'],
art246A:['special', 'provision', 'respect', 'goods', 'services', 'tax'],
art247:['power', 'parliament', 'provide', 'establishment', 'certain', 'additional', 'courts'],
art248:['residuary', 'powers', 'legislation'],
art249:['power', 'parliament', 'legislate', 'respect', 'matter', 'state', 'list', 'national', 'interest'],
art250:['power', 'parliament', 'legislate', 'respect', 'any', 'matter', 'state', 'list', 'if', 'proclamation', 'emergency', 'operation'],
art251:['inconsistency', 'between', 'laws', 'made', 'parliament', 'under', 'articles', '249', '250', 'laws', 'made', 'legislatures', 'states'],
art252:['power', 'parliament', 'legislate', 'two', 'more', 'states', 'consent', 'adoption', 'such', 'legislation', 'any', 'other', 'state'],
art253:['legislation', 'giving', 'effect', 'international', 'agreements'],
art254:['inconsistency', 'between', 'laws', 'made', 'parliament', 'laws', 'made', 'legislatures', 'states'],
art255:['requirements', 'recommendations', 'previous', 'sanctions', 'regarded', 'matters', 'procedure'],
art256:['obligation', 'states', 'union'],
art257:['control', 'union', 'over', 'states', 'certain', 'cases'],
art258:['power', 'union', 'confer', 'powers', 'etc.', 'states', 'certain', 'cases'],
art258A:['power', 'states', 'entrust', 'functions', 'union'],
art260:['jurisdiction', 'union', 'relation', 'territories', 'outside', 'india'],
art261:['public', 'acts', 'records', 'judicial', 'proceedings'],
art262:['adjudication', 'disputes', 'relating', 'waters', 'inter-state', 'rivers', 'river', 'valleys'],
art263:['provisions', 'respect', 'an', 'inter-state', 'council'],
art264:['interpretation'],
art265:['taxes', 'not', 'imposed', 'save', 'authority', 'law'],
art266:['consolidated', 'funds', 'public', 'accounts', 'india', 'states'],
art267:['contingency', 'fund'],
art268:['duties', 'levied', 'union', 'but', 'collected', 'appropriated', 'state'],
art269:['taxes', 'levied', 'collected', 'union', 'but', 'assigned', 'states'],
art269A:['levy', 'collection', 'goods', 'services', 'tax', 'course', 'inter-state', 'trade', 'commerce'],
art270:['taxes', 'levied', 'distributed', 'between', 'union', 'states'],
art271:['surcharge', 'certain', 'duties', 'taxes', 'purposes', 'union'],
art273:['grants', 'lieu', 'export', 'duty', 'jute', 'jute', 'products'],
art274:['prior', 'recommendation', 'president', 'required', 'bills', 'affecting', 'taxation', 'which', 'states', 'interested'],
art275:['grants', 'union', 'certain', 'states'],
art276:['taxes', 'professions', 'trades', 'callings', 'employments'],
art277:['savings'],
art279:['calculation', 'net', 'proceeds', 'etc'],
art279A:['goods', 'services', 'tax', 'council'],
art280:['finance', 'commission'],
art281:['recommendations', 'finance', 'commission'],
art282:['expenditure', 'defrayable', 'union', 'state', 'out', 'its', 'revenues'],
art283:['custody', 'etc.', 'consolidated', 'funds', 'contingency', 'funds', 'moneys', 'credited', 'public', 'accounts'],
art284:['custody', 'suitors', 'deposits', 'other', 'moneys', 'received', 'public', 'servants', 'courts'],
art285:['exemption', 'property', 'union', 'state', 'taxation'],
art286:['restrictions', 'imposition', 'tax', 'sale', 'purchase', 'goods'],
art287:['exemption', 'taxes', 'electricity'],
art288:['exemption', 'taxation', 'states', 'respect', 'water', 'electricity', 'certain', 'cases'],
art289:['exemption', 'property', 'income', 'state', 'union', 'taxation'],
art290:['adjustment', 'respect', 'certain', 'expenses', 'pensions'],
art290A:['annual', 'payment', 'certain', 'devaswom', 'funds'],
art292:['borrowing', 'government', 'india'],
art293:['borrowing', 'states'],
art294:['succession', 'property', 'assets', 'rights', 'liabilities', 'obligations', 'certain', 'cases'],
art295:['succession', 'property', 'assets', 'rights', 'liabilities', 'obligations', 'other', 'cases'],
art296:['property', 'accruing', 'escheat', 'laps', 'bona', 'vacantia'],
art297:['things', 'value', 'within', 'territorial', 'waters', 'continental', 'shelf', 'resources', 'exclusive', 'economic', 'zone', 'vest', 'union'],
art298:['power', 'carry', 'trade', 'etc'],
art299:['contracts'],
art300:['suits', 'proceedings'],
art300A:['persons', 'not', 'deprived', 'property', 'save', 'authority', 'law'],
art301:['freedom', 'trade', 'commerce', 'intercourse'],
art302:['power', 'parliament', 'impose', 'restrictions', 'trade', 'commerce', 'intercourse'],
art303:['restrictions', 'legislative', 'powers', 'union', 'states', 'regard', 'trade', 'commerce'],
art304:['restrictions', 'trade', 'commerce', 'intercourse', 'among', 'states'],
art305:['saving', 'existing', 'laws', 'laws', 'providing', 'state', 'monopolies'],
art307:['appointment', 'authority', 'carrying', 'out', 'purposes', 'articles', '301', '304'],
art308:['interpretation'],
art309:['recruitment', 'conditions', 'service', 'persons', 'serving', 'union', 'state'],
art310:['tenure', 'office', 'persons', 'serving', 'union', 'state'],
art311:['dismissal', 'removal', 'reduction', 'rank', 'persons', 'employed', 'civil', 'capacities', 'under', 'union', 'state'],
art312:['all-india', 'services'],
art312A:['power', 'parliament', 'vary', 'revoke', 'conditions', 'service', 'officers', 'of', 'certain', 'services'],
art313:['transitional', 'provisions'],
art314:['[repeated.'],
art315:['public', 'service', 'commissions', 'union', 'states'],
art316:['appointment', 'term', 'office', 'members'],
art317:['removal', 'suspension', 'member', 'public', 'service', 'commission'],
art318:['power', 'make', 'regulations', 'conditions', 'service', 'members', 'staff', 'commission'],
art319:['prohibition', 'holding', 'offices', 'members', 'commission', 'ceasing', 'such', 'members'],
art320:['functions', 'public', 'service', 'commissions'],
art321:['power', 'extend', 'functions', 'public', 'service', 'commissions'],
art322:['expenses', 'public', 'service', 'commissions'],
art323:['reports', 'public', 'service', 'commissions'],
art323A:['administrative', 'tribunals'],
art323B:['tribunals', 'other', 'matters'],
art324:['superintendence', 'direction', 'control', 'elections', 'vested', 'an', 'election', 'commission'],
art325:['no', 'person', 'ineligible', 'inclusion', 'claim', 'included', 'special', 'electoral', 'roll', 'grounds', 'religion', 'race', 'caste', 'sex'],
art326:['elections', 'house', 'people', 'legislative', 'assemblies', 'states', 'basis', 'adult', 'suffrage'],
art327:['power', 'parliament', 'make', 'provision', 'respect', 'elections', 'legislatures'],
art328:['power', 'legislature', 'state', 'make', 'provision', 'respect', 'elections', 'such', 'legislature'],
art329:['bar', 'interference', 'courts', 'electoral', 'matters'],
art330:['reservation', 'seats', 'scheduled', 'castes', 'scheduled', 'tribes', 'house', 'people'],
art331:['representation', 'anglo-indian', 'community', 'house', 'people'],
art332:['reservation', 'seats', 'scheduled', 'castes', 'scheduled', 'tribes', 'legislative', 'assemblies', 'states'],
art333:['representation', 'anglo-indian', 'community', 'legislative', 'assemblies', 'states'],
art334:['reservation', 'seats', 'special', 'representation', 'cease', 'after', 'sixty', 'years'],
art335:['claims', 'scheduled', 'castes', 'scheduled', 'tribes', 'services', 'posts'],
art336:['special', 'provision', 'anglo-indian', 'community', 'certain', 'services'],
art337:['special', 'provision', 'respect', 'educational', 'grants', 'benefit', 'anglo-indian', 'community'],
art338:['national', 'commission', 'scheduled', 'castes'],
art338A:['national', 'commission', 'scheduled', 'tribes'],
art338B:['national', 'commission', 'backward', 'classes'],
art339:['control', 'union', 'over', 'administration', 'scheduled', 'areas', 'welfare', 'scheduled', 'tribes'],
art340:['appointment', 'commission', 'investigate', 'conditions', 'backward', 'classes'],
art341:['scheduled', 'castes'],
art342:['scheduled', 'tribes'],
art342A:['socially', 'educationally', 'backward', 'classes'],
art343:['official', 'language', 'union'],
art344:['commission', 'committee', 'parliament', 'official', 'language'],
art345:['official', 'language', 'languages', 'state'],
art346:['official', 'language', 'communication', 'between', 'one', 'state', 'another', 'between', 'state', 'union'],
art347:['special', 'provision', 'relating', 'language', 'spoken', 'section', 'population', 'state'],
art348:['language', 'used', 'supreme', 'court', 'high', 'courts', 'acts', 'bills', 'etc'],
art349:['special', 'procedure', 'enactment', 'certain', 'laws', 'relating', 'language'],
art350:['language', 'used', 'representations', 'redress', 'grievances'],
art350A:['facilities', 'instruction', 'mother-tongue', 'primary', 'stage'],
art350B:['special', 'officer', 'linguistic', 'minorities'],
art351:['directive', 'development', 'hindi', 'language'],
art352:['proclamation', 'emergency'],
art353:['effect', 'proclamation', 'emergency'],
art354:['application', 'provisions', 'relating', 'distribution', 'revenues', 'while', 'proclamation', 'emergency', 'operation'],
art355:['duty', 'union', 'protect', 'states', 'against', 'external', 'aggression', 'internal', 'disturbance'],
art356:['provisions', 'case', 'failure', 'constitutional', 'machinery', 'states'],
art357:['exercise', 'legislative', 'powers', 'under', 'proclamation', 'issued', 'under', 'article', '356'],
art358:['suspension', 'provisions', 'article', '19', 'during', 'emergencies'],
art359:['suspension', 'enforcement', 'rights', 'conferred', 'part', 'iii', 'during', 'emergencies'],
art360:['provisions', 'financial', 'emergency'],
art361:['protection', 'president', 'governors', 'rajprakukhs'],
art361A:['protection', 'publication', 'proceedings', 'parliament', 'state', 'legislatures'],
art361B:['disqualification', 'appointment', 'remunerative', 'political', 'post'],
art363:['bar', 'interference', 'courts', 'disputes', 'arising', 'out', 'certain', 'treaties', 'agreements', 'etc'],
art363A:['recognition', 'granted', 'rulers', 'indian', 'states', 'cease', 'privy', 'purses', 'abolished'],
art364:['special', 'provisions', 'major', 'ports', 'aerodromes'],
art365:['effect', 'failure', 'comply', 'give', 'effect', 'directions', 'given', 'union'],
art366:['definitions'],
art367:['interpretation'],
art368:['power', 'parliament', 'amend', 'constitution', 'procedure', 'therefor'],
art369:['temporary', 'power', 'parliament', 'make', 'laws', 'respect', 'certain', 'matters', 'state', 'list', 'if', 'they', 'matters', 'concurrent', 'list'],
art370:['temporary', 'provisions', 'respect', 'state', 'jammu', 'kashmir'],
art371:['special', 'provision', 'respect', 'states', 'maharashtra', 'gujarat'],
art371A:['special', 'provision', 'respect', 'state', 'nagaland'],
art371B:['special', 'provision', 'respect', 'state', 'assam'],
art371C:['special', 'provision', 'respect', 'state', 'manipur'],
art371D:['special', 'provisions', 'respect', 'state', 'andhra', 'pradesh'],
art371E:['establishment', 'central', 'university', 'andhra', 'pradesh'],
art371F:['special', 'provisions', 'respect', 'state', 'sikkim'],
art371G:['special', 'provision', 'respect', 'state', 'mizoram'],
art371H:['special', 'provision', 'respect', 'state', 'arunachal', 'pradesh'],
art371I:['special', 'provision', 'respect', 'state', 'goa'],
art371J:['special', 'provision', 'respect', 'state', 'karnataka'],
art372:['continuance', 'force', 'existing', 'laws', 'their', 'adaptation'],
art372A:['power', 'president', 'adapt', 'laws'],
art373:['power', 'president', 'make', 'order', 'respect', 'persons', 'under', 'preventive', 'detention', 'certain', 'cases'],
art374:['provisions', 'judges', 'federal', 'court', 'proceedings', 'pending', 'federal', 'court', 'before', 'his', 'majesty', 'council'],
art375:['courts', 'authorities', 'officers', 'continue', 'function', 'subject', 'provisions', 'constitution'],
art376:['provisions', 'judges', 'high', 'courts'],
art377:['provisions', 'comptroller', 'auditor-general', 'india'],
art378:['provisions', 'public', 'service', 'commissions'],
art378A:['special', 'provision', 'duration', 'andhra', 'pradesh', 'legislative', 'assembly'],
art392:['power', 'president', 'remove', 'difficulties'],
art393:['short', 'title'],
art394:['commencement'],
art394A:['authoritative', 'text', 'hindi', 'language']}

var Blank=[];
for(var i=0;i<usrarr.length;i++){
    blank=finddb(usrarr[i]);
    Blank.push(blank.length);
    if(blank.length!=0){
       Blank=Blank.concat(blank);
    }
}
console.log("Combined-list : "+Blank);
return Blank;
function finddb(usr){
    var blank=[];
    var Artvalue=Object.values(Art);
    var Artkey=Object.keys(Art);
    for(var i=0;i<Artkey.length;i++){
        for(var j=0;j<Artvalue[i].length;j++){
          if(usr==Artvalue[i][j]){
              blank.push(Artkey[i]);
              console.log("Value : "+Artvalue[i][j]);
              break;
          }
        }
    }
    console.log("match-art/sec : "+blank);
    return blank;
    }
}
