function getsec{
sec1: ["1"," Title and extent of operation of the Code."],
sec2: ["2"," Punishment of offences committed within India."],
sec3: ["3"," Punishment of offences committed beyond, but which by law may be tried within, India."],
sec4: ["4"," Extension of Code to extra-territorial offences."],
sec5: ["5"," Certain laws not to be affected by this Act."],
sec6: ["6"," Definitions in the Code to be understood subject to exceptions."],
sec7: ["7"," Sense of expression once explained."],
sec8: ["8"," Gender."],
sec9: ["9"," Number."],
sec10: ["10"," “Man”, “Woman”."],
sec11: ["11"," “Person”."],
sec12: ["12"," “Public”."],
sec13: ["13"," “Queen”."],
sec14: ["14"," “Servant of Government”."],
sec15: ["15"," “British India”."],
sec16: ["16"," “Government of India”."],
sec17: ["17"," “Government”."],
sec18: ["18"," “India”."],
sec19: ["19"," “Judge”."],
sec20: ["20"," “Court of Justice”."],
sec21: ["21"," “Public servant”."],
sec22: ["22"," “Movable property”."],
sec23: ["23"," “Wrongful gain”."],
sec24: ["24"," “Dishonestly”."],
sec25: ["25"," “Fraudulently”."],
sec26: ["26"," “Reason to believe”."],
sec27: ["27"," Property in possession of wife, clerk or servant."],
sec28: ["28"," “Counterfeit”."],
sec29: ["29"," “Document”."],
sec29A: ["29A"," Electronic record."],
sec30: ["30"," “Valuable security”."],
sec31: ["31"," “A will”."],
sec32: ["32"," Words referring to acts include illegal omissions."],
sec33: ["33"," “Act”, “Omission”."],
sec34: ["34"," Acts done by several persons in furtherance of common intention."],
sec35: ["35"," When such an act is criminal by reason of its being done with a criminal knowledge or intention."],
sec36: ["36"," Effect caused partly by act and partly by omission."],
sec37: ["37"," Co-operation by doing one of several acts constituting an offence."],
sec38: ["38"," Persons concerned in criminal act may be guilty of different offences."],
sec39: ["39"," “Voluntarily”."],
sec40: ["40"," “Offence”."],
sec41: ["41"," “Special law”."],
sec42: ["42"," “Local law”."],
sec43: ["43"," “Illegal”, “Legally bound to do”."],
sec44: ["44"," “Injury”."],
sec45: ["45"," “Life”."],
sec46: ["46"," “Death”."],
sec47: ["47"," “Animal”."],
sec48: ["48"," “Vessel”."],
sec49: ["49"," “Year”, “Month”."],
sec50: ["50"," “Section”."],
sec51: ["51"," “Oath”."],
sec52: ["52"," “Good faith”."],
sec52A: ["52A"," “Harbour”."],
sec53: ["53"," “Punishments”."],
sec53A: ["53A"," Construction of reference to transportation."],
sec54: ["54"," Commutation of sentence of death."],
sec55: ["55"," Commutation of sentence of imprisonment for life."],
sec55A: ["55A"," Definition of “appropriate Government”."],
sec56: ["56"," Sentence of Europeans and Americans to penal servitude. Proviso as to sentence for term exceeding ten years but not for life."],
sec57: ["57"," Fractions of terms of punishment."],
sec58: ["58"," Offenders sentenced to transportation how dealt with until transported."],
sec59: ["59"," Transportation instead of imprisonment."],
sec60: ["60"," Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple."],
sec61: ["61"," Sentence of forfeiture of property."],
sec62: ["62"," Forfeiture of property in respect of offenders punishable with death, transportation or imprisonment."],
sec63: ["63"," Amount of fine."],
sec64: ["64"," Sentence of imprisonment for non-payment of fine."],
sec65: ["65"," Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable."],
sec66: ["66"," Description of imprisonment for non-payment of fine."],
sec67: ["67"," Imprisonment for non-payment of fine, when offence punishable with fine only."],
sec68: ["68"," Imprisonment to terminate on payment of fine."],
sec69: ["69"," Termination of imprisonment on payment of proportional part of fine."],
sec70: ["70"," Fine leviable within six years, or during imprisonment. Death not to discharge property from liability."],
sec71: ["71"," Limit of punishment of offence made up of several offences."],
sec72: ["72"," Punishment of person guilty of one of several offences, the judgment stating that it is doubtful of which."],
sec73: ["73"," Solitary confinement."],
sec74: ["74"," Limit of solitary confinement."],
sec75: ["75"," Enhanced punishment for certain offences under Chapter XII or Chapter XVII after previous conviction."],
sec76: ["76"," Act done by a person bound, or by mistake of fact believing himself bound, by law."],
sec77: ["77"," Act of Judge when acting judicially."],
sec78: ["78"," Act done pursuant to the judgment or order of Court."],
sec79: ["79"," Act done by a person justified, or by mistake of fact believing himself justified, by law."],
sec80: ["80"," Accident in doing a lawful act."],
sec81: ["81"," Act likely to cause harm, but done without criminal intent, and to prevent other harm."],
sec82: ["82"," Act of a child under seven years of age."],
sec83: ["83"," Act of a child above seven and under twelve of immature understanding."],
sec84: ["84"," Act of a person of unsound mind."],
sec85: ["85"," Act of a person incapable of judgment by reason of intoxication caused against his will."],
sec86: ["86"," Offence requiring a particular intent or knowledge committed by one who is intoxicated."],
sec87: ["87"," Act not intended and not known to be likely to cause death or grievous hurt, done by consent."],
sec88: ["88"," Act not intended to cause death, done by consent in good faith for person's benefit."],
sec89: ["89"," Act done in good faith for benefit of child or insane person, by or by consent of guardian."],
sec90: ["90"," Consent known to be given under fear or misconception."],
sec91: ["91"," Exclusion of acts which are offences independently of harm caused."],
sec92: ["92"," Act done in good faith for benefit of a person without consent."],
sec93: ["93"," Communication made in good faith."],
sec94: ["94"," Act to which a person is compelled by threats."],
sec95: ["95"," Act causing slight harm."],
sec96: ["96"," Things done in private defence."],
sec97: ["97"," Right of private defence of the body and of property."],
sec98: ["98"," Right of private defence against the act of a person of unsound mind, etc."],
sec99: ["99"," Acts against which there is no right of private defence."],
sec100: ["100"," When the right of private defence of the body extends to causing death."],
sec101: ["101"," When such right extends to causing any harm other than death."],
sec102: ["102"," Commencement and continuance of the right of private defence of the body."],
sec103: ["103"," When the right of private defence of property extends to causing death."],
sec104: ["104"," When such right extends to causing any harm other than death."],
sec105: ["105"," Commencement and continuance of the right of private defence of property."],
sec106: ["106"," Right of private defence against deadly assault when there is risk of harm to innocent person."],
sec107: ["107"," Abetment of a thing."],
sec108: ["108"," Abettor."],
sec108A: ["108A"," Abetment in India of offences outside India."],
sec109: ["109"," Punishment of abetment if the act abetted is committed in consequence and where no express provision is made for its punishment."],
sec110: ["110"," Punishment of abetment if person abetted does act with different intention from that of abettor."],
sec111: ["111"," Liability of abettor when one act abetted and different act done."],
sec112: ["112"," Abettor when liable to cumulative punishment for act abetted and for act done."],
sec113: ["113"," Liability of abettor for an effect caused by the act abetted different from that intended by the abettor."],
sec114: ["114"," Abettor present when offence is committed."],
sec115: ["115"," Abetment of offence punishable with death or imprisonment for life—if offence not committed."],
sec116: ["116"," Abetment of offence punishable with imprisonment—if offence be not committed."],
sec117: ["117"," Abetting commission of offence by the public or by more than ten persons."],
sec118: ["118"," Concealing design to commit offence punishable with death or imprisonment for life."],
sec119: ["119"," Public servant concealing design to commit offence which it is his duty to prevent."],
sec120: ["120"," Concealing design to commit offence punishable with imprisonment."],
sec120A: ["120A"," Definition of criminal conspiracy."],
sec120B: ["120B"," Punishment of criminal conspiracy."],
sec121: ["121"," Waging, or attempting to wage war, or abetting waging of war, against the Government of India."],
sec121A: ["121A"," Conspiracy to commit offences punishable by Section 121."],
sec122: ["122"," Collecting arms, etc., with intention of waging war against the Government of India."],
sec123: ["123"," Concealing with intent to facilitate design to wage war."],
sec124: ["124"," Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power."],
sec124A: ["124A"," Sedition."],
sec125: ["125"," Waging war against any Asiatic Power in alliance with the Government of India."],
sec126: ["126"," Committing depredation on territories of Power at peace with the Government of India."],
sec127: ["127"," Receiving property taken by war or depredation mentioned in Sections 125 and 126."],
sec128: ["128"," Public servant voluntarily allowing prisoner of State or war to escape."],
sec129: ["129"," Public servant negligently suffering such prisoner to escape."],
sec130: ["130"," Aiding escape of, rescuing or harbouring such prisoner."],
sec131: ["131"," Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty."],
sec132: ["132"," Abetment of mutiny, if mutiny is committed in consequence thereof."],
sec133: ["133"," Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office."],
sec134: ["134"," Abetment of such assault, if the assault is committed."],
sec135: ["135"," Abetment of desertion of soldier, sailor or airman."],
sec136: ["136"," Harbouring deserter."],
sec137: ["137"," Deserter concealed on board merchant vessel through negligence of master."],
sec138: ["138"," Abetment of act of insubordination by soldier, sailor or airman."],
sec138A: ["138A"," Application of foregoing sections to the Indian Marine Service."],
sec139: ["139"," Persons subject to certain Acts."],
sec140: ["140"," Wearing garb or carrying token used by soldier, sailor or airman."],
sec141: ["141"," Unlawful assembly."],
sec142: ["142"," Being member of unlawful assembly."],
sec143: ["143"," Punishment."],
sec144: ["144"," Joining unlawful assembly armed with deadly weapon."],
sec145: ["145"," Joining or continuing in unlawful assembly, knowing it has been commanded to disperse."],
sec146: ["146"," Rioting."],
sec147: ["147"," Punishment for rioting."],
sec148: ["148"," Rioting, armed with deadly weapon."],
sec149: ["149"," Every member of unlawful assembly guilty of offence committed in prosecution of common object."],
sec150: ["150"," Hiring, or conniving at hiring, of persons to join unlawful assembly."],
sec151: ["151"," Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse."],
sec152: ["152"," Assaulting or obstructing public servant when suppressing riot, etc."],
sec153: ["153"," Wantonly giving provocation with intent to cause riot—if rioting be committed — if not committed."],
sec153A: ["153A"," Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony."],
sec153AA: ["153AA"," Punishment for knowingly carrying arms in any procession or organising, or holding or taking part in any mass drill or mass training with arms."],
sec153B: ["153B"," Imputations, assertions prejudicial to national integration."],
sec154: ["154"," Owner or occupier of land on which an unlawful assembly is held."],
sec155: ["155"," Liability of person for whose benefit riot is committed."],
sec156: ["156"," Liability of agent of owner or occupier for whose benefit riot is committed."],
sec157: ["157"," Harbouring persons hired for an unlawful assembly."],
sec158: ["158"," Being hired to take part in an unlawful assembly or riot."],
sec159: ["159"," Affray."],
sec160: ["160"," Punishment for committing affray."],
sec161: ["161"," Public servant taking gratification other than legal remuneration in respect of an official act."],
sec162: ["162"," Taking gratification, in order, by corrupt or illegal means, to influence public servant."],
sec163: ["163"," Taking gratification, for exercise of personal influence with public servant."],
sec164: ["164"," Punishment for abetment by public servant of offences defined in Section 162 or Section 163."],
sec165: ["165"," Public servant obtaining valuable thing, without consideration, from person concerned in proceeding or business transacted by such public servant."],
sec165A: ["165A"," Punishment for abetment of offences defined in Section 161 or Section 165."],
sec166: ["166"," Public servant disobeying law, with intent to cause injury to any person."],
sec166A: ["166A"," Public servant disobeying direction under law."],
sec166B: ["166B"," Punishment for non-treatment of victim."],
sec167: ["167"," Public servant framing an incorrect document with intent to cause injury."],
sec168: ["168"," Public servant unlawfully engaging in trade."],
sec169: ["169"," Public servant unlawfully buying or bidding for property."],
sec170: ["170"," Personating a public servant."],
sec171: ["171"," Wearing garb or carrying token used by public servant with fraudulent intent."],
sec171A: ["171A"," “Candidate”, “Electoral right” defined."],
sec171B: ["171B"," Bribery."],
sec171C: ["171C"," Undue influence at elections."],
sec171D: ["171D"," Personation at elections."],
sec171E: ["171E"," Punishment for bribery."],
sec171F: ["171F"," Punishment for undue influence or personation at an election."],
sec171G: ["171G"," False statement in connection with an election."],
sec171H: ["171H"," Illegal payments in connection with an election."],
sec171I: ["171I"," Failure to keep election accounts."],
sec172: ["172"," Absconding to avoid service of summons or other proceeding."],
sec173: ["173"," Preventing service of summons or other proceeding, or preventing publication thereof."],
sec174: ["174"," Non-attendance in obedience to an order from public servant."],
sec174A: ["174A"," Non-appearance in response to a proclamation under Section 82 of Act 2 of 1974."],
sec175: ["175"," Omission to produce document or electronic record to public servant by person legally bound to produce it."],
sec176: ["176"," Omission to give notice or information to public servant by person legally bound to give it."],
sec177: ["177"," Furnishing false information."],
sec178: ["178"," Refusing oath or affirmation when duly required by public servant to make it."],
sec179: ["179"," Refusing to answer public servant authorised to question."],
sec180: ["180"," Refusing to sign statement."],
sec181: ["181"," False statement on oath or affirmation to public servant or person authorised to administer an oath or affirmation."],
sec182: ["182"," False information, with intent to cause public servant to use his lawful power to the injury of another person."],
sec183: ["183"," Resistance to the taking of property by the lawful authority of a public servant."],
sec184: ["184"," Obstructing sale of property offered for sale by authority of public servant."],
sec185: ["185"," Illegal purchase or bid for property offered for sale by authority of public servant."],
sec186: ["186"," Obstructing public servant in discharge of public functions."],
sec187: ["187"," Omission to assist public servant when bound by law to give assistance."],
sec188: ["188"," Disobedience to order duly promulgated by public servant."],
sec189: ["189"," Threat of injury to public servant."],
sec190: ["190"," Threat of injury to induce person to refrain from applying for protection to public servant."],
sec191: ["191"," Giving false evidence."],
sec192: ["192"," Fabricating false evidence."],
sec193: ["193"," Punishment for false evidence."],
sec194: ["194"," Giving or fabricating false evidence with intent to procure conviction of capital offence."],
sec195: ["195"," Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment."],
sec195A: ["195A"," Threatening any person to give false evidence."],
sec196: ["196"," Using evidence known to be false."],
sec197: ["197"," Issuing or signing false certificate."],
sec198: ["198"," Using as true a certificate known to be false."],
sec199: ["199"," False statement made in declaration which is by law receivable as evidence."],
sec200: ["200"," Using as true such declaration knowing it to be false."],
sec201: ["201"," Causing disappearance of evidence of offence, or giving false information to screen offender."],
sec202: ["202"," Intentional omission to give information of offence by person bound to inform."],
sec203: ["203"," Giving false information respecting an offence committed."],
sec204: ["204"," Destruction of document or electronic record to prevent its production as evidence."],
sec205: ["205"," False personation for purpose of act or proceeding in suit or prosecution."],
sec206: ["206"," Fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution."],
sec207: ["207"," Fraudulent claim to property to prevent its seizure as forfeited or in execution."],
sec208: ["208"," Fraudulently suffering decree for sum not due."],
sec209: ["209"," Dishonestly making false claim in Court."],
sec210: ["210"," Fraudulently obtaining decree for sum not due."],
sec211: ["211"," False charge of offence made with intent to injure."],
sec212: ["212"," Harbouring offender."],
sec213: ["213"," Taking gift, etc., to screen an offender from punishment."],
sec214: ["214"," Offering gift or restoration of property in consideration of screening offender."],
sec215: ["215"," Taking gift to help to recover stolen property, etc."],
sec216: ["216"," Harbouring offender who has escaped from custody or whose apprehension has been ordered."],
sec216A: ["216A"," Penalty for harbouring robbers or dacoits."],
sec216B: ["216B"," Definition of “harbour” in Sections 212, 216 and 216-A."],
sec217: ["217"," Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture."],
sec218: ["218"," Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture."],
sec219: ["219"," Public servant in judicial proceeding corruptly making report, etc., contrary to law."],
sec220: ["220"," Commitment for trial or confinement by person having authority who knows that he is acting contrary to law."],
sec221: ["221"," Intentional omission to apprehend on the part of public servant bound to apprehend."],
sec222: ["222"," Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence or lawfully committed."],
sec223: ["223"," Escape from confinement or custody negligently suffered by public servant."],
sec224: ["224"," Resistance or obstruction by a person to his lawful apprehension."],
sec225: ["225"," Resistance or obstruction to lawful apprehension of another person."],
sec225A: ["225A"," Omission to apprehend, or sufferance of escape, on part of public servant, in cases not otherwise provided for."],
sec225B: ["225B"," Resistance or obstruction to lawful apprehension, or escape or rescue in cases not otherwise provided for."],
sec226: ["226"," Unlawful return from transportation."],
sec227: ["227"," Violation of condition of remission of punishment."],
sec228: ["228"," Intentional insult or interruption to public servant sitting in judicial proceeding."],
sec228A: ["228A"," Disclosure of identity of the victim of certain offences, etc."],
sec229: ["229"," Personation of a juror or assessor."],
sec229A: ["229A"," Failure by person released on bail or bond to appear in Court."],
sec230: ["230"," “Coin” defined."],
sec231: ["231"," Counterfeiting coin."],
sec232: ["232"," Counterfeiting Indian coin."],
sec233: ["233"," Making or selling instrument for counterfeiting coin."],
sec234: ["234"," Making or selling instrument for counterfeiting Indian coin."],
sec235: ["235"," Possession of instrument, or material for the purpose of using the same for counterfeiting coin."],
sec236: ["236"," Abetting in India the counterfeiting out of India of coin."],
sec237: ["237"," Import or export of counterfeit coin."],
sec238: ["238"," Import or export of counterfeits of the Indian coin."],
sec239: ["239"," Delivery of coin, possessed with knowledge that it is counterfeit."],
sec240: ["240"," Delivery of Indian coin, possessed with knowledge that it is counterfeit."],
sec241: ["241"," Delivery of coin as genuine, which, when first possessed, the deliverer did not know to be counterfeit."],
sec242: ["242"," Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof."],
sec243: ["243"," Possession of Indian coin by person who knew it to be counterfeit when he became possessed thereof."],
sec244: ["244"," Person employed in mint causing coin to be of different weight or composition from that fixed by law."],
sec245: ["245"," Unlawfully taking coining instrument from mint."],
sec246: ["246"," Fraudulently or dishonestly diminishing weight or altering composition of coin."],
sec247: ["247"," Fraudulently or dishonestly diminishing weight or altering composition of Indian coin."],
sec248: ["248"," Altering appearance of coin with intent that it shall pass as coin of different description."],
sec249: ["249"," Altering appearance of Indian coin with intent that it shall pass as coin of different description."],
sec250: ["250"," Delivery of coin possessed with knowledge that it is altered."],
sec251: ["251"," Delivery of Indian coin, possessed with knowledge that it is altered."],
sec252: ["252"," Possession of coin by person who knew it to be altered when he became possessed thereof."],
sec253: ["253"," Possession of Indian coin by person who knew it to be altered when he became possessed thereof."],
sec254: ["254"," Delivery of coin as genuine which, when first possessed, the deliverer did not know to be altered."],
sec255: ["255"," Counterfeiting Government stamp."],
sec256: ["256"," Having possession of instrument or material for counterfeiting Government stamp."],
sec257: ["257"," Making or selling instrument for counterfeiting Government stamp."],
sec258: ["258"," Sale of counterfeit Government stamp."],
sec259: ["259"," Having possession of counterfeit Government stamp."],
sec260: ["260"," Using as genuine a Government stamp known to be counterfeit."],
sec261: ["261"," Effacing, writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government."],
sec262: ["262"," Using Government stamp known to have been before used."],
sec263: ["263"," Erasure of mark denoting that stamp has been used."],
sec263A: ["263A"," Prohibition of fictitious stamps."],
sec264: ["264"," Fraudulent use of false instrument for weighing."],
sec265: ["265"," Fraudulent use of false weight or measure."],
sec266: ["266"," Being in possession of false weight or measure."],
sec267: ["267"," Making or selling false weight or measure."],
sec268: ["268"," Public nuisance."],
sec269: ["269"," Negligent act likely to spread infection of disease dangerous to life."],
sec270: ["270"," Malignant act likely to spread infection of disease dangerous to life."],
sec271: ["271"," Disobedience to quarantine rule."],
sec272: ["272"," Adulteration of food or drink intended for sale."],
sec273: ["273"," Sale of noxious food or drink."],
sec274: ["274"," Adulteration of drugs."],
sec275: ["275"," Sale of adulterated drugs."],
sec276: ["276"," Sale of drug as a different drug or preparation."],
sec277: ["277"," Fouling water of public spring or reservoir."],
sec278: ["278"," Making atmosphere noxious to health."],
sec279: ["279"," Rash driving or riding on a public way."],
sec280: ["280"," Rash navigation of vessel."],
sec281: ["281"," Exhibition of false light, mark or buoy."],
sec282: ["282"," Conveying person by water for hire in unsafe or overloaded vessel."],
sec283: ["283"," Danger or obstruction in public way or line of navigation."],
sec284: ["284"," Negligent conduct with respect to poisonous substance."],
sec285: ["285"," Negligent conduct with respect to fire or combustible matter."],
sec286: ["286"," Negligent conduct with respect to explosive substance."],
sec287: ["287"," Negligent conduct with respect to machinery."],
sec288: ["288"," Negligent conduct with respect to pulling down or repairing buildings."],
sec289: ["289"," Negligent conduct with respect to animal."],
sec290: ["290"," Punishment for public nuisance in cases not otherwise provided for."],
sec291: ["291"," Continuance of nuisance after injunction to discontinue."],
sec292: ["292"," Sale, etc., of obscene books, etc."],
sec293: ["293"," Sale, etc., of obscene objects to young person."],
sec294: ["294"," Obscene acts and songs."],
sec294A: ["294A"," Keeping lottery office."],
sec295: ["295"," Injuring or defiling place of worship with intent to insult the religion of any class."],
sec295A: ["295A"," Deliberate and malicious acts intended to outrage religious feelings of any class by insulting its religion or religious beliefs."],
sec296: ["296"," Disturbing religious assembly."],
sec297: ["297"," Trespassing on burial places, etc."],
sec298: ["298"," Uttering words, etc., with deliberate intent to wound religious feelings."],
sec299: ["299"," Culpable homicide."],
sec300: ["300"," Murder."],
sec301: ["301"," Culpable homicide by causing death of person other than person whose death was intended."],
sec302: ["302"," Punishment for murder."],
sec303: ["303"," Punishment for murder by life-convict."],
sec304: ["304"," Punishment for culpable homicide not amounting to murder."],
sec304A: ["304A"," Causing death by negligence."],
sec304B: ["304B"," Dowry death."],
sec305: ["305"," Abetment of suicide of child or insane person."],
sec306: ["306"," Abetment of suicide."],
sec307: ["307"," Attempt to murder."],
sec308: ["308"," Attempt to commit culpable homicide."],
sec309: ["309"," Attempt to commit suicide."],
sec310: ["310"," Thug."],
sec311: ["311"," Punishment."],
sec312: ["312"," Causing miscarriage."],
sec313: ["313"," Causing miscarriage without woman's consent."],
sec314: ["314"," Death caused by act done with intent to cause miscarriage."],
sec315: ["315"," Act done with intent to prevent child being born alive or to cause it to die after birth."],
sec316: ["316"," Causing death of quick unborn child by act amounting to culpable homicide."],
sec317: ["317"," Exposure and abandonment of child under twelve years, by parent or person having care of it."],
sec318: ["318"," Concealment of birth by secret disposal of dead body."],
sec319: ["319"," Hurt."],
sec320: ["320"," Grievous hurt."],
sec321: ["321"," Voluntarily causing hurt."],
sec322: ["322"," Voluntarily causing grievous hurt."],
sec323: ["323"," Punishment for voluntarily causing hurt."],
sec324: ["324"," Voluntarily causing hurt by dangerous weapons or means."],
sec325: ["325"," Punishment for voluntarily causing grievous hurt."],
sec326: ["326"," Voluntarily causing grievous hurt by dangerous weapons or means."],
sec326A: ["326A"," Voluntarily causing grievous hurt by use of acid, etc."],
sec326B: ["326B"," Voluntarily throwing or attempting to throw acid."],
sec327: ["327"," Voluntarily causing hurt to extort property, or to constrain to an illegal act."],
sec328: ["328"," Causing hurt by means of poison, etc., with intent to commit an offence."],
sec329: ["329"," Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act."],
sec330: ["330"," Voluntarily causing hurt to extort confession, or to compel restoration of property."],
sec331: ["331"," Voluntarily causing grievous hurt to extort confession, or to compel restoration of property."],
sec332: ["332"," Voluntarily causing hurt to deter public servant from his duty."],
sec333: ["333"," Voluntarily causing grievous hurt to deter public servant from his duty."],
sec334: ["334"," Voluntarily causing hurt on provocation."],
sec335: ["335"," Voluntarily causing grievous hurt on provocation."],
sec336: ["336"," Act endangering life or personal safety of others."],
sec337: ["337"," Causing hurt by act endangering life or personal safety of others."],
sec338: ["338"," Causing grievous hurt by act endangering life or personal safety of others."],
sec339: ["339"," Wrongful restraint."],
sec340: ["340"," Wrongful confinement."],
sec341: ["341"," Punishment for wrongful restraint."],
sec342: ["342"," Punishment for wrongful confinement."],
sec343: ["343"," Wrongful confinement for three or more days."],
sec344: ["344"," Wrongful confinement for ten or more days."],
sec345: ["345"," Wrongful confinement of person for whose liberation writ has been issued."],
sec346: ["346"," Wrongful confinement in secret."],
sec347: ["347"," Wrongful confinement to extort property, or constrain to illegal act."],
sec348: ["348"," Wrongful confinement to extort confession, or compel restoration of property."],
sec349: ["349"," Force."],
sec350: ["350"," Criminal force."],
sec351: ["351"," Assault."],
sec352: ["352"," Punishment for assault or criminal force otherwise than on grave provocation."],
sec353: ["353"," Assault or criminal force to deter public servant from discharge of his duty."],
sec354: ["354"," Assault or criminal force to woman with intent to outrage her modesty."],
sec354A: ["354A"," Sexual harassment and punishment for sexual harassment."],
sec354B: ["354B"," Assault or use of criminal force to woman with intent to disrobe."],
sec354C: ["354C"," Voyeurism."],
sec354D: ["354D"," Stalking."],
sec355: ["355"," Assault or criminal force with intent to dishonour person, otherwise than on grave provocation."],
sec356: ["356"," Assault or criminal force in attempt to commit theft of property carried by a person."],
sec357: ["357"," Assault or criminal force in attempt wrongfully to confine a person."],
sec358: ["358"," Assault or criminal force on grave provocation."],
sec359: ["359"," Kidnapping."],
sec360: ["360"," Kidnapping from India."],
sec361: ["361"," Kidnapping from lawful guardianship."],
sec362: ["362"," Abduction."],
sec363: ["363"," Punishment for kidnapping."],
sec363A: ["363A"," Kidnapping or maiming a minor for purposes of begging."],
sec364: ["364"," Kidnapping or abducting in order to murder."],
sec364A: ["364A"," Kidnapping for ransom, etc."],
sec365: ["365"," Kidnapping or abducting with intent secretly and wrongfully to confine person."],
sec366: ["366"," Kidnapping, abducting or inducing woman to compel her marriage, etc."],
sec366A: ["366A"," Procuration of minor girl."],
sec366B: ["366B"," Importation of girl from foreign country."],
sec367: ["367"," Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc."],
sec368: ["368"," Wrongfully concealing or keeping in confinement, kidnapped or abducted person."],
sec369: ["369"," Kidnapping or abducting child under ten years with intent to steal from its person."],
sec370: ["370"," Trafficking of person."],
sec370A: ["370A"," Exploitation of a trafficked person."],
sec371: ["371"," Habitual dealing in slaves."],
sec372: ["372"," Selling minor for purposes of prostitution, etc."],
sec373: ["373"," Buying minor for purposes of prostitution, etc."],
sec374: ["374"," Unlawful compulsory labour."],
sec375: ["375"," Rape."],
sec376: ["376"," Punishment for rape."],
sec376A: ["376A"," Punishment for causing death or resulting in persistent vegetative state of victim."],
sec376AB: ["376AB"," Punishment for rape on woman under twelve years of age."],
sec376B: ["376B"," Sexual intercourse by husband upon his wife during separation."],
sec376C: ["376C"," Sexual intercourse by a person in authority."],
sec376D: ["376D"," Gang rape."],
sec376DA: ["376DA"," Punishment for gang rape on woman under sixteen years of age."],
sec376DB: ["376DB"," Punishment for gang rape on woman under twelve years of age."],
sec376E: ["376E"," Punishment for repeat offenders."],
sec377: ["377"," Unnatural offences."],
sec378: ["378"," Theft."],
sec379: ["379"," Punishment for theft."],
sec380: ["380"," Theft in dwelling house, etc."],
sec381: ["381"," Theft by clerk or servant of property in possession of master."],
sec382: ["382"," Theft after preparation made for causing death, hurt or restraint in order to the committing of the theft."],
sec383: ["383"," Extortion."],
sec384: ["384"," Punishment for extortion."],
sec385: ["385"," Putting person in fear of injury in order to commit extortion."],
sec386: ["386"," Extortion by putting a person in fear of death or grievous hurt."],
sec387: ["387"," Putting person in fear of death or of grievous hurt, in order to commit extortion."],
sec388: ["388"," Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc."],
sec389: ["389"," Putting person in fear of accusation of offence, in order to commit extortion."],
sec390: ["390"," Robbery."],
sec391: ["391"," Dacoity."],
sec392: ["392"," Punishment for robbery."],
sec393: ["393"," Attempt to commit robbery."],
sec394: ["394"," Voluntarily causing hurt in committing robbery."],
sec395: ["395"," Punishment for dacoity."],
sec396: ["396"," Dacoity with murder."],
sec397: ["397"," Robbery or dacoity, with attempt to cause death or grievous hurt."],
sec398: ["398"," Attempt to commit robbery or dacoity when armed with deadly weapon."],
sec399: ["399"," Making preparation to commit dacoity."],
sec400: ["400"," Punishment for belonging to gang of dacoits."],
sec401: ["401"," Punishment for belonging to gang of thieves."],
sec402: ["402"," Assembling for purpose of committing dacoity."],
sec403: ["403"," Dishonest misappropriation of property."],
sec404: ["404"," Dishonest misappropriation of property possessed by deceased person at the time of his death."],
sec405: ["405"," Criminal breach of trust."],
sec406: ["406"," Punishment for criminal breach of trust."],
sec407: ["407"," Criminal breach of trust by carrier, etc."],
sec408: ["408"," Criminal breach of trust by clerk or servant."],
sec409: ["409"," Criminal breach of trust by public servant, or by banker, merchant or agent."],
sec410: ["410"," Stolen property."],
sec411: ["411"," Dishonestly receiving stolen property."],
sec412: ["412"," Dishonestly receiving property stolen in the commission of a dacoity."],
sec413: ["413"," Habitually dealing in stolen property."],
sec414: ["414"," Assisting in concealment of stolen property."],
sec415: ["415"," Cheating."],
sec416: ["416"," Cheating by personation."],
sec417: ["417"," Punishment for cheating."],
sec418: ["418"," Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect."],
sec419: ["419"," Punishment for cheating by personation."],
sec420: ["420"," Cheating and dishonestly inducing delivery of property."],
sec421: ["421"," Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors."],
sec422: ["422"," Dishonestly or fraudulently preventing debt being available for creditors."],
sec423: ["423"," Dishonest or fraudulent execution of deed of transfer containing false statement of consideration."],
sec424: ["424"," Dishonest or fraudulent removal or concealment of property."],
sec425: ["425"," Mischief."],
sec426: ["426"," Punishment for mischief."],
sec427: ["427"," Mischief causing damage to the amount of fifty rupees."],
sec428: ["428"," Mischief by killing or maiming animal of the value of ten rupees."],
sec429: ["429"," Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees."],
sec430: ["430"," Mischief by injury to works of irrigation or by wrongfully diverting water."],
sec431: ["431"," Mischief by injury to public road, bridge, river or channel."],
sec432: ["432"," Mischief by causing inundation or obstruction to public drainage attended with damage."],
sec433: ["433"," Mischief by destroying, moving or rendering less useful a lighthouse or sea-mark."],
sec434: ["434"," Mischief by destroying or moving, etc., a landmark fixed by public authority."],
sec435: ["435"," Mischief by fire or explosive substance with intent to cause damage to amount of one hundred or (in case of agricultural produce) ten rupees."],
sec436: ["436"," Mischief by fire or explosive substance with intent to destroy house, etc."],
sec437: ["437"," Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden."],
sec438: ["438"," Punishment for the mischief described in Section 437 committed by fire or explosive substance."],
sec439: ["439"," Punishment for intentionally running vessel aground or ashore with intent to commit theft, etc."],
sec440: ["440"," Mischief committed after preparation made for causing death or hurt."],
sec441: ["441"," Criminal trespass."],
sec442: ["442"," House-trespass."],
sec443: ["443"," Lurking house-trespass."],
sec444: ["444"," Lurking house-trespass by night."],
sec445: ["445"," House-breaking."],
sec446: ["446"," House-breaking by night."],
sec447: ["447"," Punishment for criminal trespass."],
sec448: ["448"," Punishment for house-trespass."],
sec449: ["449"," House-trespass in order to commit offence punishable with death."],
sec450: ["450"," House-trespass in order to commit offence punishable with imprisonment for life."],
sec451: ["451"," House-trespass in order to commit offence punishable with imprisonment."],
sec452: ["452"," House-trespass after preparation for hurt, assault or wrongful restraint."],
sec453: ["453"," Punishment for lurking house-trespass or house-breaking."],
sec454: ["454"," Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment."],
sec455: ["455"," Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint."],
sec456: ["456"," Punishment for lurking house-trespass or house-breaking by night."],
sec457: ["457"," Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment."],
sec458: ["458"," Lurking house-trespass or house-breaking by night after preparation for hurt, assault, or wrongful restraint."],
sec459: ["459"," Grievous hurt caused whilst committing lurking house-trespass or house-breaking."],
sec460: ["460"," All persons jointly concerned in lurking house-trespass or house-breaking by night punishable where death or grievous hurt caused by one of them."],
sec461: ["461"," Dishonestly breaking open receptacle containing property."],
sec462: ["462"," Punishment for same offence when committed by person entrusted with custody."],
sec463: ["463"," Forgery."],
sec464: ["464"," Making a false document."],
sec465: ["465"," Punishment for forgery."],
sec466: ["466"," Forgery of record of Court or of public register, etc."],
sec467: ["467"," Forgery of valuable security, will, etc."],
sec468: ["468"," Forgery for purpose of cheating."],
sec469: ["469"," Forgery for purpose of harming reputation."],
sec470: ["470"," Forged document or electronic record."],
sec471: ["471"," Using as genuine a forged document or electronic record."],
sec472: ["472"," Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under Section 467."],
sec473: ["473"," Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise."],
sec474: ["474"," Having possession of document or electronic record described in Section 466 or 467, knowing it to be forged and intending to use it as genuine."],
sec475: ["475"," Counterfeiting device or mark used for authenticating documents described in Section 467, or possessing counterfeit marked material."],
sec476: ["476"," Counterfeiting device or mark used for authenticating documents other than those described in Section 467, or possessing counterfeit marked material."],
sec477: ["477"," Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security."],
sec477A: ["477A"," Falsification of accounts."],
sec478: ["478"," Trade mark."],
sec479: ["479"," Property mark."],
sec480: ["480"," Using a false trade mark."],
sec481: ["481"," Using a false property mark."],
sec482: ["482"," Punishment for using a false property mark."],
sec483: ["483"," Counterfeiting a property mark used by another."],
sec484: ["484"," Counterfeiting a mark used by a public servant."],
sec485: ["485"," Making or possession of any instrument for counterfeiting a property mark."],
sec486: ["486"," Selling goods marked with a counterfeit property mark."],
sec487: ["487"," Making a false mark upon any receptacle containing goods."],
sec488: ["488"," Punishment for making use of any such false mark."],
sec489: ["489"," Tampering with property mark with intent to cause injury."],
sec489A: ["489A"," Counterfeiting currency-notes or bank-notes."],
sec489B: ["489B"," Using as genuine, forged or counterfeit currency-notes or bank-notes."],
sec489C: ["489C"," Possession of forged or counterfeit currency-notes or bank-notes."],
sec489D: ["489D"," Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes."],
sec489E: ["489E"," Making or using documents resembling currency-notes or bank-notes."],
sec490: ["490"," Breach of contract of service during voyage or journey."],
sec491: ["491"," Breach of contract to attend on and supply wants of helpless person."],
sec492: ["492"," Breach of contract to serve at distant place to which servant is conveyed at master's expense."],
sec493: ["493"," Cohabitation caused by a man deceitfully inducing a belief of lawful marriage."],
sec494: ["494"," Marrying again during lifetime of husband or wife."],
sec495: ["495"," Same offence with concealment of former marriage from person with whom subsequent marriage is contracted."],
sec496: ["496"," Marriage ceremony fraudulently gone through without lawful marriage."],
sec497: ["497"," Adultery."],
sec498: ["498"," Enticing or taking away or detaining with criminal intent a married woman."],
sec498A: ["498A"," Husband or relative of husband of a woman subjecting her to cruelty."],
sec499: ["499"," Defamation."],
sec500: ["500"," Punishment for defamation."],
sec501: ["501"," Printing or engraving matter known to be defamatory."],
sec502: ["502"," Sale of printed or engraved substance containing defamatory matter."],
sec503: ["503"," Criminal intimidation."],
sec504: ["504"," Intentional insult with intent to provoke breach of the peace."],
sec505: ["505"," Statements conducing to public mischief."],
sec506: ["506"," Punishment for criminal intimidation."],
sec507: ["507"," Criminal intimidation by an anonymous communication."],
sec508: ["508"," Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure."],
sec509: ["509"," Word, gesture or act intended to insult the modesty of a woman."],
sec510: ["510"," Misconduct in public by a drunken person."],
sec511: ["511"," Punishment for attempting to commit offences punishable with imprisonment for life or other imprisonment."],
}

function getcm{
}
else if(sec<=5.0){
one="CHAPTER: 1";
two="INTRODUCTION";}
else if(sec<=52.65){
one="CHAPTER: 2";
two="GENERAL EXPLANATIONS";}
else if(sec<=75.0){
one="CHAPTER: 3";
two="OF PUNISHMENTS";}
else if(sec<=106.0){
one="CHAPTER: 4";
two="GENERAL EXCEPTIONS";
if(sec<=95.0){
three="";}
if(sec<=106.0){
three="rgpidf";}}
else if(sec<=120.0){
one="CHAPTER: 5";
two="OF ABETMENT";}
else if(sec<=120.66){
one="CHAPTER: 5A";
two="CRIMINAL CONSPIRACY";}
else if(sec<=130.0){
one="CHAPTER: 6";
two="OF OFFENCES AGAINST THE STATE";}
else if(sec<=140.0){
one="CHAPTER: 7";
two="OF OFFENCES RELATING TO THE ARMY, NAVYAND AIR FORCE";}
else if(sec<=160.0){
one="CHAPTER: 8";
two="OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY";}
else if(sec<=171.0){
one="CHAPTER: 9";
two="OF OFFENCESBY OR RELATING TO PUBLIC SERVANTS";}
else if(sec<=171.73){
one="CHAPTER: 9A";
two="OF OFFENCESRELATING TO ELECTIONS";}
else if(sec<=190.0){
one="CHAPTER: 10";
two="OF CONTEMPTS OF THE LAWFUL AUTHORITY OF PUBLIC SERVANTS";}
else if(sec<=229.65){
one="CHAPTER: 11";
two="OF FLSEEVIDENCE AND OFFENCES AGAINST PUBLIC JUSTICE";}
else if(sec<=263.65){
one="CHAPTER: 12";
two="OF OFFENCES RELATING TO COIN AND GOVERNMENT STAMPS";}
else if(sec<=267.0){
one="CHAPTER: 13";
two="OF OFFENCES RELATING TO WEIGHTS AND MEASURES";}
else if(sec<=294.65){
one="CHAPTER: 16";
two="OF OFFENCES AFFECTING THE PUBLIC HEALTH, SAFETY, CONVENIENCE, DECENCYAND MORALS";}
else if(sec<=298.0){
one="CHAPTER: 15";
two="OF OFFENCESRELATING TO RELIGION";}
else if(sec<=377.0){
one="CHAPTER: 16";
two="OF OFFENCESAFFECTINGTHE HUMAN BODY";
if(sec<=311.0){
three="ofaflf";}
else if(sec<=318.0){
three="cumsijubciepifcnbr";}
else if(sec<=338.0){
three="hr";}
else if(sec<=348.0){
three="worswocn";}
else if(sec<=358.0){
three="cifras";}
else if(sec<=374.0){
three="kdadsafrlb";}
else if(sec<=376.69){
three="Sxof";}
if(sec<=377.0){
three="unof";}}
else if(sec<=462.0){
one="CHAPTER: 17";
two="OF OFFENCES AGAINST PROPERTY";
if(sec<=382.0){
three="te";}
else if(sec<=389.0){
three="et";}
else if(sec<=402.0){
three="rbdc";}
else if(sec<=404.0){
three="cimspo";}
else if(sec<=409.0){
three="cibetu";}
else if(sec<=414.0){
three="rcsopo";}
else if(sec<=420.0){
three="ce";}
else if(sec<=424.0){
three="fadspo";}
else if(sec<=440.0){
three="ms";}
if(sec<=462.0){
three="cite";}}
else if(sec<=489.69){
one="CHAPTER: 18";
two="OF OFFENCES RELATING TO DOCUMENTS AND TO PROPERTY MARKS";
if(sec<=477.65){
three="";}
else if(sec<=489.0){
three="pomr";}
if(sec<=489.69){
three="CrBn";}}
else if(sec<=492.0){
one="CHAPTER: 21";
two="OF THE CRIMINAL BREACHOF CONTRACTS OF SERVICE";}
else if(sec<=498.0){
one="CHAPTER: 20";
two="OF OFFENCES RELATINGTO MARRIAGE";}
else if(sec<=498.65){
one="CHAPTER: 20A";
two="OF CRUELTY BY HUSBAND OR RELATIVES OF HUSBAND";}
else if(sec<=502.0){
one="CHAPTER: 21";
two="OF DEFAMATION";}
else if(sec<=510.0){
one="CHAPTER: 22";
two="OR CRIMINAL INTIMIDATION, INSULTAND ANNOYANCE";}
else if(sec<=511.0){
one="CHAPTER: 23";
two="OF ATTEMPTS OF COMMIT OFFENCES";}
return [one,two,three];}

function crang{
chp1: ["sec1","sec5"],
chp2: ["sec6","sec52A"],
chp3: ["sec53","sec75"],
chp4: ["sec76","sec106"],
chp5: ["sec107","sec120"],
chp5A: ["sec120A","sec120B"],
chp6: ["sec121","sec130"],
chp7: ["sec131","sec140"],
chp8: ["sec141","sec160"],
chp9: ["sec161","sec171"],
chp9A: ["sec171A","sec171I"],
chp10: ["sec172","sec190"],
chp11: ["sec191","sec229A"],
chp12: ["sec230","sec263A"],
chp13: ["sec264","sec267"],
chp16: ["sec268","sec294A"],
chp15: ["sec295","sec298"],
chp16: ["sec299","sec377"],
chp17: ["sec378","sec462"],
chp18: ["sec463","sec489E"],
chp21: ["sec490","sec492"],
chp20: ["sec493","sec498"],
chp20A: ["sec498A","sec498A"],
chp21: ["sec499","sec502"],
chp22: ["sec503","sec510"],
chp23: ["sec511","sec511"],
}

function mrang{
rgpidf: ["96","106"],
ofaflf: ["299","311"],
cumsijubciepifcnbr: ["312","318"],
hr: ["319","338"],
worswocn: ["339","348"],
cifras: ["349","358"],
kdadsafrlb: ["359","374"],
Sxof: ["375","376E"],
unof: ["377","377"],
te: ["378","382"],
et: ["383","389"],
rbdc: ["390","402"],
cimspo: ["403","404"],
cibetu: ["405","409"],
rcsopo: ["410","414"],
ce: ["415","420"],
fadspo: ["421","424"],
ms: ["425","440"],
cite: ["441","462"],
pomr: ["478","489"],
CrBn: ["489A","489E"],
}

function getsec{
sec1: ["1"," Title and extent of operation of the Code."],
sec2: ["2"," Punishment of offences committed within India."],
sec3: ["3"," Punishment of offences committed beyond, but which by law may be tried within, India."],
sec4: ["4"," Extension of Code to extra-territorial offences."],
sec5: ["5"," Certain laws not to be affected by this Act."],
sec6: ["6"," Definitions in the Code to be understood subject to exceptions."],
sec7: ["7"," Sense of expression once explained."],
sec8: ["8"," Gender."],
sec9: ["9"," Number."],
sec10: ["10"," “Man”, “Woman”."],
sec11: ["11"," “Person”."],
sec12: ["12"," “Public”."],
sec13: ["13"," “Queen”."],
sec14: ["14"," “Servant of Government”."],
sec15: ["15"," “British India”."],
sec16: ["16"," “Government of India”."],
sec17: ["17"," “Government”."],
sec18: ["18"," “India”."],
sec19: ["19"," “Judge”."],
sec20: ["20"," “Court of Justice”."],
sec21: ["21"," “Public servant”."],
sec22: ["22"," “Movable property”."],
sec23: ["23"," “Wrongful gain”."],
sec24: ["24"," “Dishonestly”."],
sec25: ["25"," “Fraudulently”."],
sec26: ["26"," “Reason to believe”."],
sec27: ["27"," Property in possession of wife, clerk or servant."],
sec28: ["28"," “Counterfeit”."],
sec29: ["29"," “Document”."],
sec29A: ["29A"," Electronic record."],
sec30: ["30"," “Valuable security”."],
sec31: ["31"," “A will”."],
sec32: ["32"," Words referring to acts include illegal omissions."],
sec33: ["33"," “Act”, “Omission”."],
sec34: ["34"," Acts done by several persons in furtherance of common intention."],
sec35: ["35"," When such an act is criminal by reason of its being done with a criminal knowledge or intention."],
sec36: ["36"," Effect caused partly by act and partly by omission."],
sec37: ["37"," Co-operation by doing one of several acts constituting an offence."],
sec38: ["38"," Persons concerned in criminal act may be guilty of different offences."],
sec39: ["39"," “Voluntarily”."],
sec40: ["40"," “Offence”."],
sec41: ["41"," “Special law”."],
sec42: ["42"," “Local law”."],
sec43: ["43"," “Illegal”, “Legally bound to do”."],
sec44: ["44"," “Injury”."],
sec45: ["45"," “Life”."],
sec46: ["46"," “Death”."],
sec47: ["47"," “Animal”."],
sec48: ["48"," “Vessel”."],
sec49: ["49"," “Year”, “Month”."],
sec50: ["50"," “Section”."],
sec51: ["51"," “Oath”."],
sec52: ["52"," “Good faith”."],
sec52A: ["52A"," “Harbour”."],
sec53: ["53"," “Punishments”."],
sec53A: ["53A"," Construction of reference to transportation."],
sec54: ["54"," Commutation of sentence of death."],
sec55: ["55"," Commutation of sentence of imprisonment for life."],
sec55A: ["55A"," Definition of “appropriate Government”."],
sec56: ["56"," Sentence of Europeans and Americans to penal servitude. Proviso as to sentence for term exceeding ten years but not for life."],
sec57: ["57"," Fractions of terms of punishment."],
sec58: ["58"," Offenders sentenced to transportation how dealt with until transported."],
sec59: ["59"," Transportation instead of imprisonment."],
sec60: ["60"," Sentence may be (in certain cases of imprisonment) wholly or partly rigorous or simple."],
sec61: ["61"," Sentence of forfeiture of property."],
sec62: ["62"," Forfeiture of property in respect of offenders punishable with death, transportation or imprisonment."],
sec63: ["63"," Amount of fine."],
sec64: ["64"," Sentence of imprisonment for non-payment of fine."],
sec65: ["65"," Limit to imprisonment for non-payment of fine, when imprisonment and fine awardable."],
sec66: ["66"," Description of imprisonment for non-payment of fine."],
sec67: ["67"," Imprisonment for non-payment of fine, when offence punishable with fine only."],
sec68: ["68"," Imprisonment to terminate on payment of fine."],
sec69: ["69"," Termination of imprisonment on payment of proportional part of fine."],
sec70: ["70"," Fine leviable within six years, or during imprisonment. Death not to discharge property from liability."],
sec71: ["71"," Limit of punishment of offence made up of several offences."],
sec72: ["72"," Punishment of person guilty of one of several offences, the judgment stating that it is doubtful of which."],
sec73: ["73"," Solitary confinement."],
sec74: ["74"," Limit of solitary confinement."],
sec75: ["75"," Enhanced punishment for certain offences under Chapter XII or Chapter XVII after previous conviction."],
sec76: ["76"," Act done by a person bound, or by mistake of fact believing himself bound, by law."],
sec77: ["77"," Act of Judge when acting judicially."],
sec78: ["78"," Act done pursuant to the judgment or order of Court."],
sec79: ["79"," Act done by a person justified, or by mistake of fact believing himself justified, by law."],
sec80: ["80"," Accident in doing a lawful act."],
sec81: ["81"," Act likely to cause harm, but done without criminal intent, and to prevent other harm."],
sec82: ["82"," Act of a child under seven years of age."],
sec83: ["83"," Act of a child above seven and under twelve of immature understanding."],
sec84: ["84"," Act of a person of unsound mind."],
sec85: ["85"," Act of a person incapable of judgment by reason of intoxication caused against his will."],
sec86: ["86"," Offence requiring a particular intent or knowledge committed by one who is intoxicated."],
sec87: ["87"," Act not intended and not known to be likely to cause death or grievous hurt, done by consent."],
sec88: ["88"," Act not intended to cause death, done by consent in good faith for person's benefit."],
sec89: ["89"," Act done in good faith for benefit of child or insane person, by or by consent of guardian."],
sec90: ["90"," Consent known to be given under fear or misconception."],
sec91: ["91"," Exclusion of acts which are offences independently of harm caused."],
sec92: ["92"," Act done in good faith for benefit of a person without consent."],
sec93: ["93"," Communication made in good faith."],
sec94: ["94"," Act to which a person is compelled by threats."],
sec95: ["95"," Act causing slight harm."],
sec96: ["96"," Things done in private defence."],
sec97: ["97"," Right of private defence of the body and of property."],
sec98: ["98"," Right of private defence against the act of a person of unsound mind, etc."],
sec99: ["99"," Acts against which there is no right of private defence."],
sec100: ["100"," When the right of private defence of the body extends to causing death."],
sec101: ["101"," When such right extends to causing any harm other than death."],
sec102: ["102"," Commencement and continuance of the right of private defence of the body."],
sec103: ["103"," When the right of private defence of property extends to causing death."],
sec104: ["104"," When such right extends to causing any harm other than death."],
sec105: ["105"," Commencement and continuance of the right of private defence of property."],
sec106: ["106"," Right of private defence against deadly assault when there is risk of harm to innocent person."],
sec107: ["107"," Abetment of a thing."],
sec108: ["108"," Abettor."],
sec108A: ["108A"," Abetment in India of offences outside India."],
sec109: ["109"," Punishment of abetment if the act abetted is committed in consequence and where no express provision is made for its punishment."],
sec110: ["110"," Punishment of abetment if person abetted does act with different intention from that of abettor."],
sec111: ["111"," Liability of abettor when one act abetted and different act done."],
sec112: ["112"," Abettor when liable to cumulative punishment for act abetted and for act done."],
sec113: ["113"," Liability of abettor for an effect caused by the act abetted different from that intended by the abettor."],
sec114: ["114"," Abettor present when offence is committed."],
sec115: ["115"," Abetment of offence punishable with death or imprisonment for life—if offence not committed."],
sec116: ["116"," Abetment of offence punishable with imprisonment—if offence be not committed."],
sec117: ["117"," Abetting commission of offence by the public or by more than ten persons."],
sec118: ["118"," Concealing design to commit offence punishable with death or imprisonment for life."],
sec119: ["119"," Public servant concealing design to commit offence which it is his duty to prevent."],
sec120: ["120"," Concealing design to commit offence punishable with imprisonment."],
sec120A: ["120A"," Definition of criminal conspiracy."],
sec120B: ["120B"," Punishment of criminal conspiracy."],
sec121: ["121"," Waging, or attempting to wage war, or abetting waging of war, against the Government of India."],
sec121A: ["121A"," Conspiracy to commit offences punishable by Section 121."],
sec122: ["122"," Collecting arms, etc., with intention of waging war against the Government of India."],
sec123: ["123"," Concealing with intent to facilitate design to wage war."],
sec124: ["124"," Assaulting President, Governor, etc., with intent to compel or restrain the exercise of any lawful power."],
sec124A: ["124A"," Sedition."],
sec125: ["125"," Waging war against any Asiatic Power in alliance with the Government of India."],
sec126: ["126"," Committing depredation on territories of Power at peace with the Government of India."],
sec127: ["127"," Receiving property taken by war or depredation mentioned in Sections 125 and 126."],
sec128: ["128"," Public servant voluntarily allowing prisoner of State or war to escape."],
sec129: ["129"," Public servant negligently suffering such prisoner to escape."],
sec130: ["130"," Aiding escape of, rescuing or harbouring such prisoner."],
sec131: ["131"," Abetting mutiny, or attempting to seduce a soldier, sailor or airman from his duty."],
sec132: ["132"," Abetment of mutiny, if mutiny is committed in consequence thereof."],
sec133: ["133"," Abetment of assault by soldier, sailor or airman on his superior officer, when in execution of his office."],
sec134: ["134"," Abetment of such assault, if the assault is committed."],
sec135: ["135"," Abetment of desertion of soldier, sailor or airman."],
sec136: ["136"," Harbouring deserter."],
sec137: ["137"," Deserter concealed on board merchant vessel through negligence of master."],
sec138: ["138"," Abetment of act of insubordination by soldier, sailor or airman."],
sec138A: ["138A"," Application of foregoing sections to the Indian Marine Service."],
sec139: ["139"," Persons subject to certain Acts."],
sec140: ["140"," Wearing garb or carrying token used by soldier, sailor or airman."],
sec141: ["141"," Unlawful assembly."],
sec142: ["142"," Being member of unlawful assembly."],
sec143: ["143"," Punishment."],
sec144: ["144"," Joining unlawful assembly armed with deadly weapon."],
sec145: ["145"," Joining or continuing in unlawful assembly, knowing it has been commanded to disperse."],
sec146: ["146"," Rioting."],
sec147: ["147"," Punishment for rioting."],
sec148: ["148"," Rioting, armed with deadly weapon."],
sec149: ["149"," Every member of unlawful assembly guilty of offence committed in prosecution of common object."],
sec150: ["150"," Hiring, or conniving at hiring, of persons to join unlawful assembly."],
sec151: ["151"," Knowingly joining or continuing in assembly of five or more persons after it has been commanded to disperse."],
sec152: ["152"," Assaulting or obstructing public servant when suppressing riot, etc."],
sec153: ["153"," Wantonly giving provocation with intent to cause riot—if rioting be committed — if not committed."],
sec153A: ["153A"," Promoting enmity between different groups on grounds of religion, race, place of birth, residence, language, etc., and doing acts prejudicial to maintenance of harmony."],
sec153AA: ["153AA"," Punishment for knowingly carrying arms in any procession or organising, or holding or taking part in any mass drill or mass training with arms."],
sec153B: ["153B"," Imputations, assertions prejudicial to national integration."],
sec154: ["154"," Owner or occupier of land on which an unlawful assembly is held."],
sec155: ["155"," Liability of person for whose benefit riot is committed."],
sec156: ["156"," Liability of agent of owner or occupier for whose benefit riot is committed."],
sec157: ["157"," Harbouring persons hired for an unlawful assembly."],
sec158: ["158"," Being hired to take part in an unlawful assembly or riot."],
sec159: ["159"," Affray."],
sec160: ["160"," Punishment for committing affray."],
sec161: ["161"," Public servant taking gratification other than legal remuneration in respect of an official act."],
sec162: ["162"," Taking gratification, in order, by corrupt or illegal means, to influence public servant."],
sec163: ["163"," Taking gratification, for exercise of personal influence with public servant."],
sec164: ["164"," Punishment for abetment by public servant of offences defined in Section 162 or Section 163."],
sec165: ["165"," Public servant obtaining valuable thing, without consideration, from person concerned in proceeding or business transacted by such public servant."],
sec165A: ["165A"," Punishment for abetment of offences defined in Section 161 or Section 165."],
sec166: ["166"," Public servant disobeying law, with intent to cause injury to any person."],
sec166A: ["166A"," Public servant disobeying direction under law."],
sec166B: ["166B"," Punishment for non-treatment of victim."],
sec167: ["167"," Public servant framing an incorrect document with intent to cause injury."],
sec168: ["168"," Public servant unlawfully engaging in trade."],
sec169: ["169"," Public servant unlawfully buying or bidding for property."],
sec170: ["170"," Personating a public servant."],
sec171: ["171"," Wearing garb or carrying token used by public servant with fraudulent intent."],
sec171A: ["171A"," “Candidate”, “Electoral right” defined."],
sec171B: ["171B"," Bribery."],
sec171C: ["171C"," Undue influence at elections."],
sec171D: ["171D"," Personation at elections."],
sec171E: ["171E"," Punishment for bribery."],
sec171F: ["171F"," Punishment for undue influence or personation at an election."],
sec171G: ["171G"," False statement in connection with an election."],
sec171H: ["171H"," Illegal payments in connection with an election."],
sec171I: ["171I"," Failure to keep election accounts."],
sec172: ["172"," Absconding to avoid service of summons or other proceeding."],
sec173: ["173"," Preventing service of summons or other proceeding, or preventing publication thereof."],
sec174: ["174"," Non-attendance in obedience to an order from public servant."],
sec174A: ["174A"," Non-appearance in response to a proclamation under Section 82 of Act 2 of 1974."],
sec175: ["175"," Omission to produce document or electronic record to public servant by person legally bound to produce it."],
sec176: ["176"," Omission to give notice or information to public servant by person legally bound to give it."],
sec177: ["177"," Furnishing false information."],
sec178: ["178"," Refusing oath or affirmation when duly required by public servant to make it."],
sec179: ["179"," Refusing to answer public servant authorised to question."],
sec180: ["180"," Refusing to sign statement."],
sec181: ["181"," False statement on oath or affirmation to public servant or person authorised to administer an oath or affirmation."],
sec182: ["182"," False information, with intent to cause public servant to use his lawful power to the injury of another person."],
sec183: ["183"," Resistance to the taking of property by the lawful authority of a public servant."],
sec184: ["184"," Obstructing sale of property offered for sale by authority of public servant."],
sec185: ["185"," Illegal purchase or bid for property offered for sale by authority of public servant."],
sec186: ["186"," Obstructing public servant in discharge of public functions."],
sec187: ["187"," Omission to assist public servant when bound by law to give assistance."],
sec188: ["188"," Disobedience to order duly promulgated by public servant."],
sec189: ["189"," Threat of injury to public servant."],
sec190: ["190"," Threat of injury to induce person to refrain from applying for protection to public servant."],
sec191: ["191"," Giving false evidence."],
sec192: ["192"," Fabricating false evidence."],
sec193: ["193"," Punishment for false evidence."],
sec194: ["194"," Giving or fabricating false evidence with intent to procure conviction of capital offence."],
sec195: ["195"," Giving or fabricating false evidence with intent to procure conviction of offence punishable with imprisonment for life or imprisonment."],
sec195A: ["195A"," Threatening any person to give false evidence."],
sec196: ["196"," Using evidence known to be false."],
sec197: ["197"," Issuing or signing false certificate."],
sec198: ["198"," Using as true a certificate known to be false."],
sec199: ["199"," False statement made in declaration which is by law receivable as evidence."],
sec200: ["200"," Using as true such declaration knowing it to be false."],
sec201: ["201"," Causing disappearance of evidence of offence, or giving false information to screen offender."],
sec202: ["202"," Intentional omission to give information of offence by person bound to inform."],
sec203: ["203"," Giving false information respecting an offence committed."],
sec204: ["204"," Destruction of document or electronic record to prevent its production as evidence."],
sec205: ["205"," False personation for purpose of act or proceeding in suit or prosecution."],
sec206: ["206"," Fraudulent removal or concealment of property to prevent its seizure as forfeited or in execution."],
sec207: ["207"," Fraudulent claim to property to prevent its seizure as forfeited or in execution."],
sec208: ["208"," Fraudulently suffering decree for sum not due."],
sec209: ["209"," Dishonestly making false claim in Court."],
sec210: ["210"," Fraudulently obtaining decree for sum not due."],
sec211: ["211"," False charge of offence made with intent to injure."],
sec212: ["212"," Harbouring offender."],
sec213: ["213"," Taking gift, etc., to screen an offender from punishment."],
sec214: ["214"," Offering gift or restoration of property in consideration of screening offender."],
sec215: ["215"," Taking gift to help to recover stolen property, etc."],
sec216: ["216"," Harbouring offender who has escaped from custody or whose apprehension has been ordered."],
sec216A: ["216A"," Penalty for harbouring robbers or dacoits."],
sec216B: ["216B"," Definition of “harbour” in Sections 212, 216 and 216-A."],
sec217: ["217"," Public servant disobeying direction of law with intent to save person from punishment or property from forfeiture."],
sec218: ["218"," Public servant framing incorrect record or writing with intent to save person from punishment or property from forfeiture."],
sec219: ["219"," Public servant in judicial proceeding corruptly making report, etc., contrary to law."],
sec220: ["220"," Commitment for trial or confinement by person having authority who knows that he is acting contrary to law."],
sec221: ["221"," Intentional omission to apprehend on the part of public servant bound to apprehend."],
sec222: ["222"," Intentional omission to apprehend on the part of public servant bound to apprehend person under sentence or lawfully committed."],
sec223: ["223"," Escape from confinement or custody negligently suffered by public servant."],
sec224: ["224"," Resistance or obstruction by a person to his lawful apprehension."],
sec225: ["225"," Resistance or obstruction to lawful apprehension of another person."],
sec225A: ["225A"," Omission to apprehend, or sufferance of escape, on part of public servant, in cases not otherwise provided for."],
sec225B: ["225B"," Resistance or obstruction to lawful apprehension, or escape or rescue in cases not otherwise provided for."],
sec226: ["226"," Unlawful return from transportation."],
sec227: ["227"," Violation of condition of remission of punishment."],
sec228: ["228"," Intentional insult or interruption to public servant sitting in judicial proceeding."],
sec228A: ["228A"," Disclosure of identity of the victim of certain offences, etc."],
sec229: ["229"," Personation of a juror or assessor."],
sec229A: ["229A"," Failure by person released on bail or bond to appear in Court."],
sec230: ["230"," “Coin” defined."],
sec231: ["231"," Counterfeiting coin."],
sec232: ["232"," Counterfeiting Indian coin."],
sec233: ["233"," Making or selling instrument for counterfeiting coin."],
sec234: ["234"," Making or selling instrument for counterfeiting Indian coin."],
sec235: ["235"," Possession of instrument, or material for the purpose of using the same for counterfeiting coin."],
sec236: ["236"," Abetting in India the counterfeiting out of India of coin."],
sec237: ["237"," Import or export of counterfeit coin."],
sec238: ["238"," Import or export of counterfeits of the Indian coin."],
sec239: ["239"," Delivery of coin, possessed with knowledge that it is counterfeit."],
sec240: ["240"," Delivery of Indian coin, possessed with knowledge that it is counterfeit."],
sec241: ["241"," Delivery of coin as genuine, which, when first possessed, the deliverer did not know to be counterfeit."],
sec242: ["242"," Possession of counterfeit coin by person who knew it to be counterfeit when he became possessed thereof."],
sec243: ["243"," Possession of Indian coin by person who knew it to be counterfeit when he became possessed thereof."],
sec244: ["244"," Person employed in mint causing coin to be of different weight or composition from that fixed by law."],
sec245: ["245"," Unlawfully taking coining instrument from mint."],
sec246: ["246"," Fraudulently or dishonestly diminishing weight or altering composition of coin."],
sec247: ["247"," Fraudulently or dishonestly diminishing weight or altering composition of Indian coin."],
sec248: ["248"," Altering appearance of coin with intent that it shall pass as coin of different description."],
sec249: ["249"," Altering appearance of Indian coin with intent that it shall pass as coin of different description."],
sec250: ["250"," Delivery of coin possessed with knowledge that it is altered."],
sec251: ["251"," Delivery of Indian coin, possessed with knowledge that it is altered."],
sec252: ["252"," Possession of coin by person who knew it to be altered when he became possessed thereof."],
sec253: ["253"," Possession of Indian coin by person who knew it to be altered when he became possessed thereof."],
sec254: ["254"," Delivery of coin as genuine which, when first possessed, the deliverer did not know to be altered."],
sec255: ["255"," Counterfeiting Government stamp."],
sec256: ["256"," Having possession of instrument or material for counterfeiting Government stamp."],
sec257: ["257"," Making or selling instrument for counterfeiting Government stamp."],
sec258: ["258"," Sale of counterfeit Government stamp."],
sec259: ["259"," Having possession of counterfeit Government stamp."],
sec260: ["260"," Using as genuine a Government stamp known to be counterfeit."],
sec261: ["261"," Effacing, writing from substance bearing Government stamp, or removing from document a stamp used for it, with intent to cause loss to Government."],
sec262: ["262"," Using Government stamp known to have been before used."],
sec263: ["263"," Erasure of mark denoting that stamp has been used."],
sec263A: ["263A"," Prohibition of fictitious stamps."],
sec264: ["264"," Fraudulent use of false instrument for weighing."],
sec265: ["265"," Fraudulent use of false weight or measure."],
sec266: ["266"," Being in possession of false weight or measure."],
sec267: ["267"," Making or selling false weight or measure."],
sec268: ["268"," Public nuisance."],
sec269: ["269"," Negligent act likely to spread infection of disease dangerous to life."],
sec270: ["270"," Malignant act likely to spread infection of disease dangerous to life."],
sec271: ["271"," Disobedience to quarantine rule."],
sec272: ["272"," Adulteration of food or drink intended for sale."],
sec273: ["273"," Sale of noxious food or drink."],
sec274: ["274"," Adulteration of drugs."],
sec275: ["275"," Sale of adulterated drugs."],
sec276: ["276"," Sale of drug as a different drug or preparation."],
sec277: ["277"," Fouling water of public spring or reservoir."],
sec278: ["278"," Making atmosphere noxious to health."],
sec279: ["279"," Rash driving or riding on a public way."],
sec280: ["280"," Rash navigation of vessel."],
sec281: ["281"," Exhibition of false light, mark or buoy."],
sec282: ["282"," Conveying person by water for hire in unsafe or overloaded vessel."],
sec283: ["283"," Danger or obstruction in public way or line of navigation."],
sec284: ["284"," Negligent conduct with respect to poisonous substance."],
sec285: ["285"," Negligent conduct with respect to fire or combustible matter."],
sec286: ["286"," Negligent conduct with respect to explosive substance."],
sec287: ["287"," Negligent conduct with respect to machinery."],
sec288: ["288"," Negligent conduct with respect to pulling down or repairing buildings."],
sec289: ["289"," Negligent conduct with respect to animal."],
sec290: ["290"," Punishment for public nuisance in cases not otherwise provided for."],
sec291: ["291"," Continuance of nuisance after injunction to discontinue."],
sec292: ["292"," Sale, etc., of obscene books, etc."],
sec293: ["293"," Sale, etc., of obscene objects to young person."],
sec294: ["294"," Obscene acts and songs."],
sec294A: ["294A"," Keeping lottery office."],
sec295: ["295"," Injuring or defiling place of worship with intent to insult the religion of any class."],
sec295A: ["295A"," Deliberate and malicious acts intended to outrage religious feelings of any class by insulting its religion or religious beliefs."],
sec296: ["296"," Disturbing religious assembly."],
sec297: ["297"," Trespassing on burial places, etc."],
sec298: ["298"," Uttering words, etc., with deliberate intent to wound religious feelings."],
sec299: ["299"," Culpable homicide."],
sec300: ["300"," Murder."],
sec301: ["301"," Culpable homicide by causing death of person other than person whose death was intended."],
sec302: ["302"," Punishment for murder."],
sec303: ["303"," Punishment for murder by life-convict."],
sec304: ["304"," Punishment for culpable homicide not amounting to murder."],
sec304A: ["304A"," Causing death by negligence."],
sec304B: ["304B"," Dowry death."],
sec305: ["305"," Abetment of suicide of child or insane person."],
sec306: ["306"," Abetment of suicide."],
sec307: ["307"," Attempt to murder."],
sec308: ["308"," Attempt to commit culpable homicide."],
sec309: ["309"," Attempt to commit suicide."],
sec310: ["310"," Thug."],
sec311: ["311"," Punishment."],
sec312: ["312"," Causing miscarriage."],
sec313: ["313"," Causing miscarriage without woman's consent."],
sec314: ["314"," Death caused by act done with intent to cause miscarriage."],
sec315: ["315"," Act done with intent to prevent child being born alive or to cause it to die after birth."],
sec316: ["316"," Causing death of quick unborn child by act amounting to culpable homicide."],
sec317: ["317"," Exposure and abandonment of child under twelve years, by parent or person having care of it."],
sec318: ["318"," Concealment of birth by secret disposal of dead body."],
sec319: ["319"," Hurt."],
sec320: ["320"," Grievous hurt."],
sec321: ["321"," Voluntarily causing hurt."],
sec322: ["322"," Voluntarily causing grievous hurt."],
sec323: ["323"," Punishment for voluntarily causing hurt."],
sec324: ["324"," Voluntarily causing hurt by dangerous weapons or means."],
sec325: ["325"," Punishment for voluntarily causing grievous hurt."],
sec326: ["326"," Voluntarily causing grievous hurt by dangerous weapons or means."],
sec326A: ["326A"," Voluntarily causing grievous hurt by use of acid, etc."],
sec326B: ["326B"," Voluntarily throwing or attempting to throw acid."],
sec327: ["327"," Voluntarily causing hurt to extort property, or to constrain to an illegal act."],
sec328: ["328"," Causing hurt by means of poison, etc., with intent to commit an offence."],
sec329: ["329"," Voluntarily causing grievous hurt to extort property, or to constrain to an illegal act."],
sec330: ["330"," Voluntarily causing hurt to extort confession, or to compel restoration of property."],
sec331: ["331"," Voluntarily causing grievous hurt to extort confession, or to compel restoration of property."],
sec332: ["332"," Voluntarily causing hurt to deter public servant from his duty."],
sec333: ["333"," Voluntarily causing grievous hurt to deter public servant from his duty."],
sec334: ["334"," Voluntarily causing hurt on provocation."],
sec335: ["335"," Voluntarily causing grievous hurt on provocation."],
sec336: ["336"," Act endangering life or personal safety of others."],
sec337: ["337"," Causing hurt by act endangering life or personal safety of others."],
sec338: ["338"," Causing grievous hurt by act endangering life or personal safety of others."],
sec339: ["339"," Wrongful restraint."],
sec340: ["340"," Wrongful confinement."],
sec341: ["341"," Punishment for wrongful restraint."],
sec342: ["342"," Punishment for wrongful confinement."],
sec343: ["343"," Wrongful confinement for three or more days."],
sec344: ["344"," Wrongful confinement for ten or more days."],
sec345: ["345"," Wrongful confinement of person for whose liberation writ has been issued."],
sec346: ["346"," Wrongful confinement in secret."],
sec347: ["347"," Wrongful confinement to extort property, or constrain to illegal act."],
sec348: ["348"," Wrongful confinement to extort confession, or compel restoration of property."],
sec349: ["349"," Force."],
sec350: ["350"," Criminal force."],
sec351: ["351"," Assault."],
sec352: ["352"," Punishment for assault or criminal force otherwise than on grave provocation."],
sec353: ["353"," Assault or criminal force to deter public servant from discharge of his duty."],
sec354: ["354"," Assault or criminal force to woman with intent to outrage her modesty."],
sec354A: ["354A"," Sexual harassment and punishment for sexual harassment."],
sec354B: ["354B"," Assault or use of criminal force to woman with intent to disrobe."],
sec354C: ["354C"," Voyeurism."],
sec354D: ["354D"," Stalking."],
sec355: ["355"," Assault or criminal force with intent to dishonour person, otherwise than on grave provocation."],
sec356: ["356"," Assault or criminal force in attempt to commit theft of property carried by a person."],
sec357: ["357"," Assault or criminal force in attempt wrongfully to confine a person."],
sec358: ["358"," Assault or criminal force on grave provocation."],
sec359: ["359"," Kidnapping."],
sec360: ["360"," Kidnapping from India."],
sec361: ["361"," Kidnapping from lawful guardianship."],
sec362: ["362"," Abduction."],
sec363: ["363"," Punishment for kidnapping."],
sec363A: ["363A"," Kidnapping or maiming a minor for purposes of begging."],
sec364: ["364"," Kidnapping or abducting in order to murder."],
sec364A: ["364A"," Kidnapping for ransom, etc."],
sec365: ["365"," Kidnapping or abducting with intent secretly and wrongfully to confine person."],
sec366: ["366"," Kidnapping, abducting or inducing woman to compel her marriage, etc."],
sec366A: ["366A"," Procuration of minor girl."],
sec366B: ["366B"," Importation of girl from foreign country."],
sec367: ["367"," Kidnapping or abducting in order to subject person to grievous hurt, slavery, etc."],
sec368: ["368"," Wrongfully concealing or keeping in confinement, kidnapped or abducted person."],
sec369: ["369"," Kidnapping or abducting child under ten years with intent to steal from its person."],
sec370: ["370"," Trafficking of person."],
sec370A: ["370A"," Exploitation of a trafficked person."],
sec371: ["371"," Habitual dealing in slaves."],
sec372: ["372"," Selling minor for purposes of prostitution, etc."],
sec373: ["373"," Buying minor for purposes of prostitution, etc."],
sec374: ["374"," Unlawful compulsory labour."],
sec375: ["375"," Rape."],
sec376: ["376"," Punishment for rape."],
sec376A: ["376A"," Punishment for causing death or resulting in persistent vegetative state of victim."],
sec376AB: ["376AB"," Punishment for rape on woman under twelve years of age."],
sec376B: ["376B"," Sexual intercourse by husband upon his wife during separation."],
sec376C: ["376C"," Sexual intercourse by a person in authority."],
sec376D: ["376D"," Gang rape."],
sec376DA: ["376DA"," Punishment for gang rape on woman under sixteen years of age."],
sec376DB: ["376DB"," Punishment for gang rape on woman under twelve years of age."],
sec376E: ["376E"," Punishment for repeat offenders."],
sec377: ["377"," Unnatural offences."],
sec378: ["378"," Theft."],
sec379: ["379"," Punishment for theft."],
sec380: ["380"," Theft in dwelling house, etc."],
sec381: ["381"," Theft by clerk or servant of property in possession of master."],
sec382: ["382"," Theft after preparation made for causing death, hurt or restraint in order to the committing of the theft."],
sec383: ["383"," Extortion."],
sec384: ["384"," Punishment for extortion."],
sec385: ["385"," Putting person in fear of injury in order to commit extortion."],
sec386: ["386"," Extortion by putting a person in fear of death or grievous hurt."],
sec387: ["387"," Putting person in fear of death or of grievous hurt, in order to commit extortion."],
sec388: ["388"," Extortion by threat of accusation of an offence punishable with death or imprisonment for life, etc."],
sec389: ["389"," Putting person in fear of accusation of offence, in order to commit extortion."],
sec390: ["390"," Robbery."],
sec391: ["391"," Dacoity."],
sec392: ["392"," Punishment for robbery."],
sec393: ["393"," Attempt to commit robbery."],
sec394: ["394"," Voluntarily causing hurt in committing robbery."],
sec395: ["395"," Punishment for dacoity."],
sec396: ["396"," Dacoity with murder."],
sec397: ["397"," Robbery or dacoity, with attempt to cause death or grievous hurt."],
sec398: ["398"," Attempt to commit robbery or dacoity when armed with deadly weapon."],
sec399: ["399"," Making preparation to commit dacoity."],
sec400: ["400"," Punishment for belonging to gang of dacoits."],
sec401: ["401"," Punishment for belonging to gang of thieves."],
sec402: ["402"," Assembling for purpose of committing dacoity."],
sec403: ["403"," Dishonest misappropriation of property."],
sec404: ["404"," Dishonest misappropriation of property possessed by deceased person at the time of his death."],
sec405: ["405"," Criminal breach of trust."],
sec406: ["406"," Punishment for criminal breach of trust."],
sec407: ["407"," Criminal breach of trust by carrier, etc."],
sec408: ["408"," Criminal breach of trust by clerk or servant."],
sec409: ["409"," Criminal breach of trust by public servant, or by banker, merchant or agent."],
sec410: ["410"," Stolen property."],
sec411: ["411"," Dishonestly receiving stolen property."],
sec412: ["412"," Dishonestly receiving property stolen in the commission of a dacoity."],
sec413: ["413"," Habitually dealing in stolen property."],
sec414: ["414"," Assisting in concealment of stolen property."],
sec415: ["415"," Cheating."],
sec416: ["416"," Cheating by personation."],
sec417: ["417"," Punishment for cheating."],
sec418: ["418"," Cheating with knowledge that wrongful loss may ensue to person whose interest offender is bound to protect."],
sec419: ["419"," Punishment for cheating by personation."],
sec420: ["420"," Cheating and dishonestly inducing delivery of property."],
sec421: ["421"," Dishonest or fraudulent removal or concealment of property to prevent distribution among creditors."],
sec422: ["422"," Dishonestly or fraudulently preventing debt being available for creditors."],
sec423: ["423"," Dishonest or fraudulent execution of deed of transfer containing false statement of consideration."],
sec424: ["424"," Dishonest or fraudulent removal or concealment of property."],
sec425: ["425"," Mischief."],
sec426: ["426"," Punishment for mischief."],
sec427: ["427"," Mischief causing damage to the amount of fifty rupees."],
sec428: ["428"," Mischief by killing or maiming animal of the value of ten rupees."],
sec429: ["429"," Mischief by killing or maiming cattle, etc., of any value or any animal of the value of fifty rupees."],
sec430: ["430"," Mischief by injury to works of irrigation or by wrongfully diverting water."],
sec431: ["431"," Mischief by injury to public road, bridge, river or channel."],
sec432: ["432"," Mischief by causing inundation or obstruction to public drainage attended with damage."],
sec433: ["433"," Mischief by destroying, moving or rendering less useful a lighthouse or sea-mark."],
sec434: ["434"," Mischief by destroying or moving, etc., a landmark fixed by public authority."],
sec435: ["435"," Mischief by fire or explosive substance with intent to cause damage to amount of one hundred or (in case of agricultural produce) ten rupees."],
sec436: ["436"," Mischief by fire or explosive substance with intent to destroy house, etc."],
sec437: ["437"," Mischief with intent to destroy or make unsafe a decked vessel or one of twenty tons burden."],
sec438: ["438"," Punishment for the mischief described in Section 437 committed by fire or explosive substance."],
sec439: ["439"," Punishment for intentionally running vessel aground or ashore with intent to commit theft, etc."],
sec440: ["440"," Mischief committed after preparation made for causing death or hurt."],
sec441: ["441"," Criminal trespass."],
sec442: ["442"," House-trespass."],
sec443: ["443"," Lurking house-trespass."],
sec444: ["444"," Lurking house-trespass by night."],
sec445: ["445"," House-breaking."],
sec446: ["446"," House-breaking by night."],
sec447: ["447"," Punishment for criminal trespass."],
sec448: ["448"," Punishment for house-trespass."],
sec449: ["449"," House-trespass in order to commit offence punishable with death."],
sec450: ["450"," House-trespass in order to commit offence punishable with imprisonment for life."],
sec451: ["451"," House-trespass in order to commit offence punishable with imprisonment."],
sec452: ["452"," House-trespass after preparation for hurt, assault or wrongful restraint."],
sec453: ["453"," Punishment for lurking house-trespass or house-breaking."],
sec454: ["454"," Lurking house-trespass or house-breaking in order to commit offence punishable with imprisonment."],
sec455: ["455"," Lurking house-trespass or house-breaking after preparation for hurt, assault or wrongful restraint."],
sec456: ["456"," Punishment for lurking house-trespass or house-breaking by night."],
sec457: ["457"," Lurking house-trespass or house-breaking by night in order to commit offence punishable with imprisonment."],
sec458: ["458"," Lurking house-trespass or house-breaking by night after preparation for hurt, assault, or wrongful restraint."],
sec459: ["459"," Grievous hurt caused whilst committing lurking house-trespass or house-breaking."],
sec460: ["460"," All persons jointly concerned in lurking house-trespass or house-breaking by night punishable where death or grievous hurt caused by one of them."],
sec461: ["461"," Dishonestly breaking open receptacle containing property."],
sec462: ["462"," Punishment for same offence when committed by person entrusted with custody."],
sec463: ["463"," Forgery."],
sec464: ["464"," Making a false document."],
sec465: ["465"," Punishment for forgery."],
sec466: ["466"," Forgery of record of Court or of public register, etc."],
sec467: ["467"," Forgery of valuable security, will, etc."],
sec468: ["468"," Forgery for purpose of cheating."],
sec469: ["469"," Forgery for purpose of harming reputation."],
sec470: ["470"," Forged document or electronic record."],
sec471: ["471"," Using as genuine a forged document or electronic record."],
sec472: ["472"," Making or possessing counterfeit seal, etc., with intent to commit forgery punishable under Section 467."],
sec473: ["473"," Making or possessing counterfeit seal, etc., with intent to commit forgery punishable otherwise."],
sec474: ["474"," Having possession of document or electronic record described in Section 466 or 467, knowing it to be forged and intending to use it as genuine."],
sec475: ["475"," Counterfeiting device or mark used for authenticating documents described in Section 467, or possessing counterfeit marked material."],
sec476: ["476"," Counterfeiting device or mark used for authenticating documents other than those described in Section 467, or possessing counterfeit marked material."],
sec477: ["477"," Fraudulent cancellation, destruction, etc., of will, authority to adopt, or valuable security."],
sec477A: ["477A"," Falsification of accounts."],
sec478: ["478"," Trade mark."],
sec479: ["479"," Property mark."],
sec480: ["480"," Using a false trade mark."],
sec481: ["481"," Using a false property mark."],
sec482: ["482"," Punishment for using a false property mark."],
sec483: ["483"," Counterfeiting a property mark used by another."],
sec484: ["484"," Counterfeiting a mark used by a public servant."],
sec485: ["485"," Making or possession of any instrument for counterfeiting a property mark."],
sec486: ["486"," Selling goods marked with a counterfeit property mark."],
sec487: ["487"," Making a false mark upon any receptacle containing goods."],
sec488: ["488"," Punishment for making use of any such false mark."],
sec489: ["489"," Tampering with property mark with intent to cause injury."],
sec489A: ["489A"," Counterfeiting currency-notes or bank-notes."],
sec489B: ["489B"," Using as genuine, forged or counterfeit currency-notes or bank-notes."],
sec489C: ["489C"," Possession of forged or counterfeit currency-notes or bank-notes."],
sec489D: ["489D"," Making or possessing instruments or materials for forging or counterfeiting currency-notes or bank-notes."],
sec489E: ["489E"," Making or using documents resembling currency-notes or bank-notes."],
sec490: ["490"," Breach of contract of service during voyage or journey."],
sec491: ["491"," Breach of contract to attend on and supply wants of helpless person."],
sec492: ["492"," Breach of contract to serve at distant place to which servant is conveyed at master's expense."],
sec493: ["493"," Cohabitation caused by a man deceitfully inducing a belief of lawful marriage."],
sec494: ["494"," Marrying again during lifetime of husband or wife."],
sec495: ["495"," Same offence with concealment of former marriage from person with whom subsequent marriage is contracted."],
sec496: ["496"," Marriage ceremony fraudulently gone through without lawful marriage."],
sec497: ["497"," Adultery."],
sec498: ["498"," Enticing or taking away or detaining with criminal intent a married woman."],
sec498A: ["498A"," Husband or relative of husband of a woman subjecting her to cruelty."],
sec499: ["499"," Defamation."],
sec500: ["500"," Punishment for defamation."],
sec501: ["501"," Printing or engraving matter known to be defamatory."],
sec502: ["502"," Sale of printed or engraved substance containing defamatory matter."],
sec503: ["503"," Criminal intimidation."],
sec504: ["504"," Intentional insult with intent to provoke breach of the peace."],
sec505: ["505"," Statements conducing to public mischief."],
sec506: ["506"," Punishment for criminal intimidation."],
sec507: ["507"," Criminal intimidation by an anonymous communication."],
sec508: ["508"," Act caused by inducing person to believe that he will be rendered an object of the Divine displeasure."],
sec509: ["509"," Word, gesture or act intended to insult the modesty of a woman."],
sec510: ["510"," Misconduct in public by a drunken person."],
sec511: ["511"," Punishment for attempting to commit offences punishable with imprisonment for life or other imprisonment."],
}

function getcm{
}
else if(sec<=5.0){
one="CHAPTER: 1";
two="INTRODUCTION";}
else if(sec<=52.65){
one="CHAPTER: 2";
two="GENERAL EXPLANATIONS";}
else if(sec<=75.0){
one="CHAPTER: 3";
two="OF PUNISHMENTS";}
else if(sec<=106.0){
one="CHAPTER: 4";
two="GENERAL EXCEPTIONS";
if(sec<=95.0){
three="";}
if(sec<=106.0){
three="rgpidf";}}
else if(sec<=120.0){
one="CHAPTER: 5";
two="OF ABETMENT";}
else if(sec<=120.66){
one="CHAPTER: 5A";
two="CRIMINAL CONSPIRACY";}
else if(sec<=130.0){
one="CHAPTER: 6";
two="OF OFFENCES AGAINST THE STATE";}
else if(sec<=140.0){
one="CHAPTER: 7";
two="OF OFFENCES RELATING TO THE ARMY, NAVYAND AIR FORCE";}
else if(sec<=160.0){
one="CHAPTER: 8";
two="OF OFFENCES AGAINST THE PUBLIC TRANQUILLITY";}
else if(sec<=171.0){
one="CHAPTER: 9";
two="OF OFFENCESBY OR RELATING TO PUBLIC SERVANTS";}
else if(sec<=171.73){
one="CHAPTER: 9A";
two="OF OFFENCESRELATING TO ELECTIONS";}
else if(sec<=190.0){
one="CHAPTER: 10";
two="OF CONTEMPTS OF THE LAWFUL AUTHORITY OF PUBLIC SERVANTS";}
else if(sec<=229.65){
one="CHAPTER: 11";
two="OF FLSEEVIDENCE AND OFFENCES AGAINST PUBLIC JUSTICE";}
else if(sec<=263.65){
one="CHAPTER: 12";
two="OF OFFENCES RELATING TO COIN AND GOVERNMENT STAMPS";}
else if(sec<=267.0){
one="CHAPTER: 13";
two="OF OFFENCES RELATING TO WEIGHTS AND MEASURES";}
else if(sec<=294.65){
one="CHAPTER: 16";
two="OF OFFENCES AFFECTING THE PUBLIC HEALTH, SAFETY, CONVENIENCE, DECENCYAND MORALS";}
else if(sec<=298.0){
one="CHAPTER: 15";
two="OF OFFENCESRELATING TO RELIGION";}
else if(sec<=377.0){
one="CHAPTER: 16";
two="OF OFFENCESAFFECTINGTHE HUMAN BODY";
if(sec<=311.0){
three="ofaflf";}
else if(sec<=318.0){
three="cumsijubciepifcnbr";}
else if(sec<=338.0){
three="hr";}
else if(sec<=348.0){
three="worswocn";}
else if(sec<=358.0){
three="cifras";}
else if(sec<=374.0){
three="kdadsafrlb";}
else if(sec<=376.69){
three="sxof";}
if(sec<=377.0){
three="unof";}}
else if(sec<=462.0){
one="CHAPTER: 17";
two="OF OFFENCES AGAINST PROPERTY";
if(sec<=382.0){
three="te";}
else if(sec<=389.0){
three="et";}
else if(sec<=402.0){
three="rbdc";}
else if(sec<=404.0){
three="cimspo";}
else if(sec<=409.0){
three="cibetu";}
else if(sec<=414.0){
three="rcsopo";}
else if(sec<=420.0){
three="ce";}
else if(sec<=424.0){
three="fadspo";}
else if(sec<=440.0){
three="ms";}
if(sec<=462.0){
three="cite";}}
else if(sec<=489.69){
one="CHAPTER: 18";
two="OF OFFENCES RELATING TO DOCUMENTS AND TO PROPERTY MARKS";
if(sec<=477.65){
three="";}
else if(sec<=489.0){
three="pomr";}
if(sec<=489.69){
three="crbn";}}
else if(sec<=492.0){
one="CHAPTER: 21";
two="OF THE CRIMINAL BREACHOF CONTRACTS OF SERVICE";}
else if(sec<=498.0){
one="CHAPTER: 20";
two="OF OFFENCES RELATINGTO MARRIAGE";}
else if(sec<=498.65){
one="CHAPTER: 20A";
two="OF CRUELTY BY HUSBAND OR RELATIVES OF HUSBAND";}
else if(sec<=502.0){
one="CHAPTER: 21";
two="OF DEFAMATION";}
else if(sec<=510.0){
one="CHAPTER: 22";
two="OR CRIMINAL INTIMIDATION, INSULTAND ANNOYANCE";}
else if(sec<=511.0){
one="CHAPTER: 23";
two="OF ATTEMPTS OF COMMIT OFFENCES";}
return [one,two,three];}

function crang{
chp1: ["sec1","sec5"],
chp2: ["sec6","sec52A"],
chp3: ["sec53","sec75"],
chp4: ["sec76","sec106"],
chp5: ["sec107","sec120"],
chp5A: ["sec120A","sec120B"],
chp6: ["sec121","sec130"],
chp7: ["sec131","sec140"],
chp8: ["sec141","sec160"],
chp9: ["sec161","sec171"],
chp9A: ["sec171A","sec171I"],
chp10: ["sec172","sec190"],
chp11: ["sec191","sec229A"],
chp12: ["sec230","sec263A"],
chp13: ["sec264","sec267"],
chp16: ["sec268","sec294A"],
chp15: ["sec295","sec298"],
chp16: ["sec299","sec377"],
chp17: ["sec378","sec462"],
chp18: ["sec463","sec489E"],
chp21: ["sec490","sec492"],
chp20: ["sec493","sec498"],
chp20A: ["sec498A","sec498A"],
chp21: ["sec499","sec502"],
chp22: ["sec503","sec510"],
chp23: ["sec511","sec511"],
}

function mrang{
rgpidf: ["96","106"],
ofaflf: ["299","311"],
cumsijubciepifcnbr: ["312","318"],
hr: ["319","338"],
worswocn: ["339","348"],
cifras: ["349","358"],
kdadsafrlb: ["359","374"],
sxof: ["375","376E"],
unof: ["377","377"],
te: ["378","382"],
et: ["383","389"],
rbdc: ["390","402"],
cimspo: ["403","404"],
cibetu: ["405","409"],
rcsopo: ["410","414"],
ce: ["415","420"],
fadspo: ["421","424"],
ms: ["425","440"],
cite: ["441","462"],
pomr: ["478","489"],
crbn: ["489A","489E"],
}

